kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: sxcm-cluster-console-project
  annotations:
    openshift.io/display-name: STARTX cluster Console (admin)
    description: Deploy cluster-wide resources to personnalize OCP web console according to sxcm definitions
    iconClass: icon-openshift
    tags: startx,cluster,config,admin,console
    openshift.io/provider-display-name: STARTX
    openshift.io/generated-by: sxcm
    sxcm_console_timeout: "5"
  labels:
    template: sxcm-cluster-console-project
    app.kubernetes.io/name: "sxcm-cluster-console-project"
    app.kubernetes.io/managed-by: sxcm
message: |-
  Your console personnalisation for project ${SCOPE}-${ENV} is done.

  Scope             : ${SCOPE}
  Cluster           : ${CLUSTER}
labels:
  template: sxcm-cluster-console-project
  app.kubernetes.io/managed-by: sxcm
objects:
- kind: Application
  apiVersion: argoproj.io/v1alpha1
  metadata:
    name: startx-cluster-console
    namespace: "${ARGOCD_NS}"
    labels:  &basic_labels
      app.startx.fr/scope: "${SCOPE}"
      app.startx.fr/cluster: "${CLUSTER}"
      app.startx.fr/component: "cluster-console"
      app.kubernetes.io/name: "startx-cluster-console-application"
      app.kubernetes.io/part-of: ${CLUSTER}
      app.kubernetes.io/version: "${VERSION}"
      app.kubernetes.io/component: "cluster-console"
    annotations: &basic_annotations
      openshift.io/generated-by: sxcm
      # argocd.argoproj.io/manifest-generate-paths: .
    finalizers:
      - resources-finalizer.argocd.argoproj.io
  spec:
    destination:
      namespace: "${NS}"
      server: 'https://kubernetes.default.svc'
    info:
      - name: teammail
        value: dev@startx.fr
    project: cluster-admin
    source:
      path: charts/cluster-console/
      repoURL: 'https://github.com/startxfr/helm-repository.git'
      targetRevision: master
      helm:
        valueFiles:
          - values-${TUNNING_PROFILE}.yaml
        parameters:
          - name: context.scope
            value: "${SCOPE}"
          - name: context.cluster
            value: "${CLUSTER}"
          - name: context.environment
            value: "${ENV}"
          - name: context.version
            value: "${VERSION}"
    syncPolicy: 
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=false
        - Validate=true
      retry:
        limit: 2
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 20s
    ignoreDifferences:
      - kind: ConfigMap
        name: custom-logo
        namespace: "openshift-console"
        jsonPointers:
          - /
parameters:
  - name: ARGOCD_NS
    displayName: The namespace where argocd server goes to
    description: "Namespace to place argocd server to"
    value: startx-argocd
  - name: NS
    displayName: The namespace where objects goes to
    description: "Namespace to place objects to"
    value: openshift-config
  - name: SCOPE
    displayName: Project scope
    description: "Project scope (ex: sxv4)"
    value: startx
  - name: CLUSTER
    displayName: Cluster name
    description: "Name of the current cluster  (ex: sxsf)"
    value: sxsf
  - name: ENV
    displayName: Project environment
    description: "Project environment (ex: dev, factory, preprod or prod)"
    value: dev
  - name: VERSION
    displayName: Project version
    description: "Project deployed release"
    value: 3.9.x-dev
  - name: CLUSTER_PROFILE
    displayName: Name of the cluster profile
    description: "The name of the cluster profile"
    value: default
  - name: TUNNING_PROFILE
    displayName: Name of the personnalisation to perform
    description: "The name of the personnalisation to execute (could be manutan, cisval, lumiplan, monaco)"
    value: startx
  - name: DOCKERHUB_LOGIN
    displayName: Login to use for pulling images from the dockerhub registry
    description: "The login to use for pulling images from the dockerhub registry"
    value: myDockerhubLogin
  - name: DOCKERHUB_PWD
    displayName: Password to use for pulling images from the dockerhub registry
    description: "The Password coresponding to the login for pulling images from the dockerhub registry"
    value: myDockerhubPassword
  - name: QUAYIO_LOGIN
    displayName: Login to use for pulling images from the quay.io registry
    description: "The login to use for pulling images from the quay.io registry"
    value: myQuayioLogin
  - name: QUAYIO_PWD
    displayName: Password to use for pulling images from the quay.io registry
    description: "The Password coresponding to the login for pulling images from the quay.ioi registry"
    value: myQuayioPassword
