#!/bin/bash


# Install openshift installer in /usr/local/bin/
function installClusterInstaller {
    echo -e "Start openshift installer \e[32minstallation\e[0m of \e[1m$SXCM_OCPI_RELEASE\e[0m"
    rm -rf $SXCM_OCPI_TMP /tmp/$SXCM_OCPI_PACKAGE &> /dev/null
    mkdir $SXCM_OCPI_TMP &> /dev/null
    cd /tmp &> /dev/null
    echo -e "Downloading \e[1m$SXCM_OCPI_RELEASE\e[0m openshift installer from \e[1m$SXCM_OCPI_BRANCH\e[0m "
    wget $SXCM_OCPI_URL
    echo -e "Unarchive \e[1m$SXCM_OCPI_RELEASE\e[0m openshift installer in \e[1m$SXCM_OCPI_TMP\e[0m"
    mv $SXCM_OCPI_PACKAGE $SXCM_OCPI_TMP/ &> /dev/null
    cd - &> /dev/null
    cd $SXCM_OCPI_TMP &> /dev/null
    tar xzvf $SXCM_OCPI_PACKAGE &> /dev/null
    echo -e "Install binary \e[1m$SXCM_OCPI_RELEASE\e[0m openshift installer in \e[1m$SXCM_OCPI_BIN\e[0m"
    sudo mv openshift-install $SXCM_OCPI_BIN &> /dev/null
    cd - &> /dev/null
    echo -e "Cleanup of \e[1m$SXCM_OCPI_RELEASE\e[0m openshift installer"
    rm -rf $SXCM_OCPI_TMP /tmp/$SXCM_OCPI_PACKAGE &> /dev/null
    SXCM_OCPI_RELEASE=$(openshift-install version | grep openshift-install | cut -dv -f2)
}

# Install openshift installer if not present in /usr/local/bin/
function installClusterInstallerIfNotPresent {
    if [[ ! -x "$SXCM_OCPI_BIN" ]]; then
        echo -e "Start openshift installer \e[32minstallation\e[0m (no $SXCM_OCPI_BIN)"
        installClusterInstaller
    else
        SXCM_OCPI_RELEASE=$(openshift-install version | grep openshift-install | cut -dv -f2)
    fi
}

# get list cluster configuration
function getClusterConfigurationList {
    local LIST=$(ls -d $SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/*/ 2>/dev/null)
    local COUNT=$(echo $LIST | wc -w)
    local OUT=""
    if [[ $COUNT -gt 0 ]]; then
        for configuration in $LIST
        do
            foo=${configuration#"$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/"}
            foo=${foo%"/"}
            OUT="${OUT} ${foo}"
        done
        echo $OUT
    fi
}

# read the content of the cluster description in an install-config.yaml
function getClusterDescription {
    local descClusterConfig=$(grep -A0 -P '^    descriptionClusterconfig:' $1 | cut -d: -f2 | sed -r 's/["]+//g')
    local desc=$(grep -A0 -P '^    description:' $1 | cut -d: -f2 | sed -r 's/["]+//g')
    if [[ $2 == 'desc' ]]
    then
        echo "$desc"
    elif [[ $2 == 'service' ]]
    then
        echo "$descClusterConfig"
    else
        echo "$desc - $descClusterConfig"
    fi
}

# read the content of the cluster descriptionTab in an install-config.yaml
function getClusterDescriptionTab {
    local descClusterConfig=$(grep -A0 -P '^    descriptionClusterconfig:' $1 | cut -d: -f2 | sed -r 's/["]+//g')
    local desc=$(grep -A0 -P '^    descriptionTab:' $1 | cut -d: -f2 | sed -r 's/["]+//g')
    local hcost=$(getClusterHourlyCost $1)
    echo "$desc | $hcost | $descClusterConfig"
}

# read the content of the cluster description in an install-config.yaml
function getClusterHourlyCost {
    echo $(grep -A0 -P '^    hourlyCost:' $1 | cut -d: -f2 | sed -r 's/["]+//g')
}

# create cluster resources
function updateClusterResources {
    local cn=$1
    echo -e "Cluster \e[1m$cn\e[0m : \e[32mUpdate\e[0m the cluster resources \e[93m(admin)\e[0m"
    doUpsertClusterResources update $cn
}

# create cluster resources
function createClusterResources {
    local cn=$1
    echo -e "Cluster \e[1m$cn\e[0m : \e[32mCreate\e[0m the cluster resources \e[93m(admin)\e[0m"
    doUpsertClusterResources create $cn
}

# create/update cluster resources
function doUpsertClusterResources {
    local UPSERT=$1
    local cn=$2
    local CLUSTER_CONF=""
    local clusterconfig=""
    local currentress=""
    local RESOURCEDIR_PATH=$SXCM_RESOURCES_PATH
    local CLUSTER_CONFDIR=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    local CLUSTERID=local CLUSTERID=$(oc get machineset -n openshift-machine-api -o jsonpath="{.items[0].metadata.labels}" | cut -d \" -f 4)
    local clusterName=$(echo $SXCM_CLUSTER_URL | sed -e 's|https://||g')
    if [[ -r $CLUSTER_CONFDIR/install-config.yaml ]]
    then
        CLUSTER_CONF=$CLUSTER_CONFDIR/install-config.yaml
    else
        CLUSTER_CONF=$CLUSTER_CONFDIR/install-config.yaml.back
    fi
    if [[ ! -r $CLUSTER_CONF ]]
    then
        echo -e "No cluster config found at \e[1m$CLUSTER_CONF\e[0m for loading \e[1m$cn\e[0m cluster resources"
    else 
        clusterconfig=$(grep -A0 -P '^    clusterconfig:'  $CLUSTER_CONF | cut -d: -f2 | tr "," "\n")
        CLUSTER_REGION=$(cat $CLUSTER_CONF | yq .platform.aws.region -cr)
        CLUSTER_PROFILE=$(cat $CLUSTER_CONF | yq .platform.aws.userTags.profile -cr)
        recordAdminTokenFromCreatedCluster $cn
        for resource in $clusterconfig
        do
            currentress=""
            local CLUSTERTIMEOUT=$(cat $RESOURCEDIR_PATH/$resource.yml | yq .metadata.annotations.sxv4_console_timeout -cr)
            if [[ -r $RESOURCEDIR_PATH/$resource.yml ]]
            then
                currentress="$resource"
                echo -e "${UPSERT} \e[1m$resource\e[0m cluster resource in cluster \e[1m$cn\e[0m \e[93m(admin)\e[0m"
                if [[ "$resource" == "quay" || "$resource" == "3scale" || "$resource" == "argocd-deploy" || "$resource" == "argocd-apps" ]]
                then
                    oc process -f $RESOURCEDIR_PATH/$resource.yml --local -o yaml \
                    -p RHN_USER=$SXCM_RHN_USER \
                    -p RHN_PASSWORD=$SXCM_RHN_PASSWORD \
                    -p SCOPE=$SXCM_CLUSTER_SCOPE \
                    -p CLUSTER=$cn \
                    -p ENV=$SXCM_ENV \
                    -p VERSION=$SXCM_VERSION \
                    -p AWS_ZONE=$SXCM_AWS_ZONE \
                    -p AWS_ACCESS_ID=$SXCM_AWS_ID \
                    -p AWS_ACCESS_KEY=$SXCM_AWS_KEY \
                    -p AWS_SMTP_USER=$SXCM_AWS_SMTP_USER \
                    -p AWS_SMTP_PASSWORD=$SXCM_AWS_SMTP_PASSWORD \
                    -p AWS_SMTP_ZONE=$SXCM_AWS_SMTPZONE \
                    -p AWS_SMTP_FROM=$SXCM_AWS_SMTPFROM \
                    -p CLUSTER_PROFILE=$CLUSTER_PROFILE \
                    | oc apply $SXCM_OCAPPLY_OPTS --token=$SXCM_CLUSTER_ADMIN_TOKEN --cluster=$clusterName -f -
                elif [[ "$resource" == "machine" ]]
                then
                    oc process -f $RESOURCEDIR_PATH/$resource.yml --local -o yaml \
                    -p SCOPE=$SXCM_CLUSTER_SCOPE \
                    -p CLUSTER=$cn \
                    -p ENV=$SXCM_ENV \
                    -p VERSION=$SXCM_VERSION \
                    -p CLUSTERID=$CLUSTERID \
                    -p CLUSTER_REGION=$CLUSTER_REGION \
                    -p CLUSTER_PROFILE=$CLUSTER_PROFILE \
                    | oc apply $SXCM_OCAPPLY_OPTS --token=$SXCM_CLUSTER_ADMIN_TOKEN --cluster=$clusterName -f -
                else
                    oc process -f $RESOURCEDIR_PATH/$resource.yml --local -o yaml \
                    -p SCOPE=$SXCM_CLUSTER_SCOPE \
                    -p CLUSTER=$cn \
                    -p ENV=$SXCM_ENV \
                    -p VERSION=$SXCM_VERSION \
                    -p CLUSTER_PROFILE=$CLUSTER_PROFILE \
                    | oc apply $SXCM_OCAPPLY_OPTS --token=$SXCM_CLUSTER_ADMIN_TOKEN --cluster=$clusterName -f -
                fi
                if [[ "${UPSERT}" == "create" ]]; then
                    echo -e "wait ${CLUSTERTIMEOUT}sec for operator dependencies start"
                    temporize $CLUSTERTIMEOUT 5
                else
                    echo -e "wait 5sec for operator dependencies update"
                    temporize 2 1
                fi
            fi
            if [[ -d $RESOURCEDIR_PATH/$resource ]]
            then
                local ressscript="upsert.sh"
                if [[ -x $RESOURCEDIR_PATH/$resource/$ressscript ]]
                then
                    currentress="$ressscript"
                    echo -e "${UPSERT} \e[1m$resource\e[0m cluster resource in cluster \e[1m$cn\e[0m \e[93m(admin)\e[0m"
                    . $RESOURCEDIR_PATH/$resource/$ressscript $cn $SXCM_CLUSTER_SCOPE $SXCM_ENV $SXCM_VERSION $SXCM_CLUSTER_ADMIN_TOKEN $clusterName
                    if [[ "${UPSERT}" == "create" ]]; then
                        echo -e "wait ${CLUSTERTIMEOUT}sec for deployment dependencies start"
                        temporize $CLUSTERTIMEOUT 5
                    fi
                else 
                    echo -e "No \e[1m$resource\e[0m cluster resource found at \e[1m$RESOURCEDIR_PATH/$resource/$ressscript\e[0 or is executable"
                fi
            fi
            if [[ "$currentress" == "" ]]
            then
                echo -e "No \e[1m$resource\e[0m cluster resource found at \e[1m$RESOURCEDIR_PATH/$resource.yml\e[0m"
            fi
        done
    fi
}

# Set openshift-install cluster admin credentials
function setCredentialsFromCreatedCluster {
    local cn=$1
    local CLUSTER_CONFDIR=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    cd $CLUSTER_CONFDIR &> /dev/null
    SXCM_CLUSTER_URL=$(cat auth/kubeconfig | grep server | cut -d: -f2-10 | xargs)
    appendIndividualClusterConf $cn SXCM_CLUSTER_URL $SXCM_CLUSTER_URL
    appendIndividualClusterConf $cn SXCM_CLUSTER_NAME $cn
    reloadIndividualClusterConf $cn
    cd - &> /dev/null
}

# Get openshift-install cluster admin credentials
function getCredentialsFromCreatedCluster {
    local cn=$1
    local CLUSTER_CONFDIR=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    setCredentialsFromCreatedCluster $cn
    cd $CLUSTER_CONFDIR &> /dev/null
    SXCM_ADM=kubeadmin
    SXCM_ADMPWD=$(cat auth/kubeadmin-password)
    cd - &> /dev/null
}

# Record SXCM_CLUSTER_ADMIN_TOKEN for created cluster in sxv4 configuration
function recordAdminTokenFromCreatedCluster {
    local cn=$1
    getCredentialsFromCreatedCluster $cn
    local clusterName=$(echo $SXCM_CLUSTER_URL | sed -e 's|https://||g')
    oc login --insecure-skip-tls-verify -u $SXCM_ADM -p "$SXCM_ADMPWD" $SXCM_CLUSTER_URL  &> /dev/null
    if [[ "$?" != 0 ]]; then
        echo -e "Cluster \e[1m$cn\e[0m : \e[1m\e[31mCould not login\e[0m to \e[1m$cn\e[0m with user \e[1m$SXCM_ADM\e[0m"
        echo -e "Log to openshift cluster first \e[90;4moc login -u $SXCM_ADM -p <pwd> $SXCM_CLUSTER_URL\e[0m"
        echo -e "try to run \e[90;4msxcm info\e[0m"
        exit 1;
    else
        tokena=`oc whoami -t`
        SXCM_CLUSTER_ADMIN_TOKEN=$tokena
        appendIndividualClusterConf $cn SXCM_CLUSTER_ADMIN_TOKEN $tokena
        reloadIndividualClusterConf $cn
        echo -e "Cluster \e[1m$cn\e[0m : Logged to \e[1m$cn\e[0m with user \e[1m$SXCM_ADM\e[0m (capture token)"
        echo -e "use this connection for example with \e[90;4moc get projects --token=$tokena --cluster=$clusterName\e[0m"
    fi
}

# create cluster configuration
function doClusterConfigurationCreate {
    local cn=$1
    local PROFILE=$2
    echo -e "\e[1m\e[34mStart\e[0m creation process for cluster \e[1m$cn\e[0m"
    if [[ "$cn" == "" ]]; then
        echo -en "Cluster name [$cn] : "
        read cn
    fi
    if [[ $cn == '' ]]; then
        cn="mycluster"
    fi
    if [[ $PROFILE == '' ]]; then
        PROFILE="default"
    fi
    local CLUSTER_CONFDIR=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    local SXCM_GIT_BRANCH=$cn
    if [[ -r $CLUSTER_CONFDIR/install-config.yaml ]]; then
        echo -en "  Do you want to reset \e[1m$cn\e[0m cluster configuration [y/N] : "
        read removeConfig
        if [[ "$removeConfig" == "y" ]]; then
            cd $CLUSTER_CONFDIR &> /dev/null
            git checkout $cn &> /dev/null
            rm -f $CLUSTER_CONFDIR/install-config.ya* &> /dev/null
            git add . &> /dev/null
            git commit -m "[$cn] Reset the $cn cluster" &> /dev/null
            git push origin $cn
            cd - &> /dev/null
            echo -e "\e[1m\e[35mReset\e[0m cluster \e[1m$cn\e[0m configuration"
        else
            exit;
        fi
    fi
    if [[ -z "${SXCM_GIT_REPO}" || -z "${SXCM_GIT_BRANCH}" ]]; then
        doSetupGit
    fi
    if [[ -z "${SXCM_RHN_USER}" || -z "${SXCM_RHN_PASSWORD}" || -z "${SXCM_RHN_EMAIL}" || -z "${SXCM_RHN_PULLSECRET}" ]]; then
        doSetupRedhat
    fi
    if [[ -r $SXCM_PROFILES_PATH/install-config-$PROFILE.yml ]]; then
        git clone $SXCM_GIT_REPO $CLUSTER_CONFDIR
        echo -e "  \e[32mcreated\e[0m cluster directory \e[1m$CLUSTER_CONFDIR\e[0m from \e[1m$SXCM_GIT_BRANCH\e[0m branch in \e[1m$SXCM_GIT_REPO\e[0m repository"
        cd $CLUSTER_CONFDIR &> /dev/null
        echo -e "  \e[33mupdated\e[0m git repository configuration in \e[1m$CLUSTER_CONFDIR\e[0m"
        git checkout $SXCM_GIT_BRANCH &> /dev/null
        git checkout $SXCM_GIT_BRANCH_MAIN &> /dev/null
        git checkout $cn &> /dev/null
        if [[ "$?" != "0" ]]; then
            git checkout $SXCM_GIT_BRANCH_MAIN &> /dev/null
            git branch $cn &> /dev/null
            git checkout $cn &> /dev/null
            git push origin $cn
            echo -e "  \e[32mcreated\e[0m git repository branch \e[1m$cn\e[0m based on \e[1m$SXCM_GIT_BRANCH_MAIN\e[0m branch"
        fi
        git checkout $cn &> /dev/null
        echo -e "  \e[33mswitched\e[0m to branch \e[1m$cn\e[0m"
        touch $CLUSTER_CONFDIR/$SXCM_USER_CONF_FILE &> /dev/null
        appendIndividualClusterConf $cn SXCM_GIT_REPO $SXCM_GIT_REPO
        appendIndividualClusterConf $cn SXCM_GIT_BRANCH $SXCM_GIT_BRANCH
        appendIndividualClusterConf $cn SXCM_RHN_USER $SXCM_RHN_USER
        # appendIndividualClusterConf $cn SXCM_RHN_PASSWORD $SXCM_RHN_PASSWORD
        appendIndividualClusterConf $cn SXCM_RHN_EMAIL $SXCM_RHN_EMAIL
        # appendIndividualClusterConf $cn SXCM_RHN_PULLSECRET $SXCM_RHN_PULLSECRET
        appendIndividualClusterConf $cn SXCM_CLUSTER_NAME $cn
        appendIndividualClusterConf $cn PROFILE $PROFILE
        reloadIndividualClusterConf $cn
        cp $SXCM_USER_SSH_DIR/id_rsa.pub $SXCM_USER_SSH_DIR/id_rsa $CLUSTER_CONFDIR/ &> /dev/null
        chown 400 $CLUSTER_CONFDIR/id_rsa.pub $CLUSTER_CONFDIR/id_rsa &> /dev/null
        eval "$(ssh-agent -s)" &>/dev/null
        `ssh-add $CLUSTER_CONFDIR/id_rsa &> /dev/null` &> /dev/null
        echo -e "  \e[32madded\e[0m ssh key \e[1m$CLUSTER_CONFDIR/id_rsa\e[0m for this cluster"
        cp $SXCM_PROFILES_PATH/install-config-$PROFILE.yml $CLUSTER_CONFDIR/install-config.yaml &> /dev/null
        sed -i "s|__mycluster__|$cn|g" $CLUSTER_CONFDIR/install-config.yaml &> /dev/null
        sed -i "s|__ocpPullSecret__|$SXCM_RHN_PULLSECRET|g" $CLUSTER_CONFDIR/install-config.yaml &> /dev/null
        local SSH_PUBLICKEY=$(cat $CLUSTER_CONFDIR/id_rsa.pub)
        sed -i "s|__ocpSshPublickey__|${SSH_PUBLICKEY}|g" $CLUSTER_CONFDIR/install-config.yaml
        cp $CLUSTER_CONFDIR/install-config.yaml $CLUSTER_CONFDIR/install-config.yaml.back &> /dev/null
        git add . &> /dev/null
        git commit -am "[$cn] Create the $cn cluster" &> /dev/null
        git push origin $cn
        cd - &> /dev/null
        echo -e "  \e[32mrecorded\e[0m cluster configuration based on \e[1m$PROFILE\e[0m profile"
        setActiveCluster $cn
        echo -e "\e[1m\e[32mSet active\e[0m cluster set to \e[1m$cn\e[0m"
    else
        echo -e "  No profile named \e[1m$PROFILE\e[0m found"
        echo -e "  you could run \e[90;4msxcm profiles\e[0m to get a list of available profiles"
        echo -en "  Do you want to create a new cluster without profile [Y/n] : "
        read newCluster
        if [[ "$newCluster" == "n" ]]; then
            echo -en "  Do you want to create a new cluster using \e[1mdefault\e[0m profile [Y/n] : "
            read newCluster
            if [[ "$newCluster" == "n" ]]; then
                echo -e "  Cluster \e[1m$cn\e[0m \e[31mwas not created\e[0m"
                exit 1;
            else
                doClusterConfigurationCreate $cn default
            fi
        else
            installClusterInstallerIfNotPresent
            echo -e "  Start \e[1m$SXCM_OCPI_RELEASE\e[0m openshift installer \e[32mconfiguration\e[0m"
            if [[ -r $CLUSTER_CONFDIR/metadata.json ]]; then
                echo -e "  Could not configure because cluster is \e[1malready configured\e[0m"
                echo -e "  you should run \e[90;4msxcm destroy $cn\e[0m before"
                exit 1;
            fi
            if [[ -r $CLUSTER_CONFDIR/terraform.tfstate ]]; then
                echo -en "  Do you want to connect to the running cluster [Y/n] : "
                read connectOCP
                echo -e ""
                if [[ "$connectOCP" == "n" ]]; then
                    echo -e "  Could not \e[36mconfigure\e[0m because cluster is already running"
                    echo -e "  you should run \e[90;4msxcm destroy $cn\e[0m before"
                    exit 1;
                else
                    cd $CLUSTER_CONFDIR &> /dev/null
                    git checkout $cn &> /dev/null
                    recordAdminTokenFromCreatedCluster $cn
                    git add . &> /dev/null
                    git commit -m "[$cn] Add new token to the $cn cluster" &> /dev/null
                    git push origin $cn
                    cd - &> /dev/null
                    exit;
                fi
            fi
            if [[ -r $CLUSTER_CONFDIR/install-config.yaml ]]; then
                echo -en "  Do you want to reset cluster configuration [y/N] : "
                read removeConfig
                if [[ "$removeConfig" == "y" ]]; then
                    cd $CLUSTER_CONFDIR &> /dev/null
                    git checkout $cn &> /dev/null
                    rm -f $CLUSTER_CONFDIR/install-config.yaml &> /dev/null
                    rm -f $CLUSTER_CONFDIR/install-config.yaml.back &> /dev/null
                    rm -f $CLUSTER_CONFDIR/auth &> /dev/null
                    git add . &> /dev/null
                    git commit -m "[$cn] Reset the $cn cluster" &> /dev/null
                    git push origin $cn
                    cd - &> /dev/null
                    echo -e "  Cluster configuration \e[1m$cn\e[0m \e[35mreset\e[0m "
                else
                    exit;
                fi
            fi
            cd $CLUSTER_CONFDIR &> /dev/null
            git checkout $cn &> /dev/null
            openshift-install create install-config &> /dev/null
            git add . &> /dev/null
            git commit -m "[$cn] Record the $cn cluster config" &> /dev/null
            git push origin $cn
            cd - &> /dev/null
        fi
    fi
}

# import cluster configuration
function doClusterConfigurationImport {
    local cn=$1
    local branch=$2
    rm -rf /tmp/sxcm-repo  &> /dev/null
    echo -e "\e[1m\e[34mStart\e[0m import process for cluster \e[1m$cn\e[0m"
    if [[ "$cn" == "" ]]; then
        echo -en "Cluster name [mycluster] : "
        read cn
    fi
    if [[ $cn == '' ]]; then
        cn="mycluster"
    fi
    if [[ $branch == '' ]]; then
        branch="$cn"
    fi
    local CLUSTER_CONFDIR=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    local SXCM_GIT_BRANCH=$branch
    if [[ -d $CLUSTER_CONFDIR ]]; then
        echo -e "  Cluster \e[1m$cn\e[0m \e[31mis already managed\e[0m. Could not import \e[1m$cn\e[0m"
        exit;
    else
        echo -e "  Cluster \e[1m$cn\e[0m \e[32mis not managed\e[0m"
    fi
    git clone $SXCM_GIT_REPO /tmp/sxcm-repo
    if [[ $? -gt 0 ]]; then
        echo -e "  Repository \e[1m$SXCM_GIT_REPO\e[0m \e[31mis not clonable\e[0m. Could not import \e[1m$cn\e[0m"
        exit;
    else
        echo -e "  Repository \e[1m$SXCM_GIT_REPO\e[0m \e[32mis cloned\e[0m"
    fi
    cd /tmp/sxcm-repo  &> /dev/null
    git checkout $SXCM_GIT_BRANCH  &> /dev/null
    if [[ $? -gt 0 ]]; then
        echo -e "  Cluster state defined in branch \e[1m$SXCM_GIT_BRANCH\e[0m \e[31mdoesn't exist\e[0m. Could not import \e[1m$cn\e[0m"
        exit;
    else
        echo -e "  Cluster state defined in branch \e[1m$SXCM_GIT_BRANCH\e[0m \e[32mis cloned\e[0m"
    fi
    mv /tmp/sxcm-repo $CLUSTER_CONFDIR &> /dev/null
    rm -rf /tmp/sxcm-repo  &> /dev/null
    echo -e "  Cluster \e[1m$cn\e[0m is \e[32mimported\e[0m from \e[1m$SXCM_GIT_BRANCH\e[0m cluster state "
    cd -  &> /dev/null
    # cd $CLUSTER_CONFDIR &> /dev/null
    # git checkout $branch &> /dev/null
    # git add . &> /dev/null
    # git commit -m "[$cn] Record the $cn cluster install config in branch $branch" &> /dev/null
    # git push origin $cn
    # cd - &> /dev/null
    echo -e "  \e[1m\e[32mImport\e[0m of \e[1m$cn\e[0m cluster is \e[34mdone\e[0m"
}

# export cluster configuration
function doClusterConfigurationExport {
    local cn=$1
    if [[ "$cn" == "" ]]; then
        cn=`getActiveCluster`
    fi
    echo -e "\e[1m\e[34mStart\e[0m export process for cluster \e[1m$cn\e[0m"
    reloadIndividualClusterConf $cn
    local CLUSTER_CONFDIR=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    if [[ ! -d $CLUSTER_CONFDIR ]]; then
        echo -e "  Cluster \e[1m$cn\e[0m \e[31mdoesn't exist\e[0m. Could not import \e[1m$cn\e[0m"
        exit;
    elif [[ ! -d $CLUSTER_CONFDIR/.git ]]; then
        echo -e "  Cluster \e[1m$cn\e[0m \e[31mis not managed\e[0m by git. Could not export \e[1m$cn\e[0m"
        exit;
    fi
    git checkout $SXCM_GIT_BRANCH  &> /dev/null
    if [[ $? -gt 0 ]]; then
        echo -e "  Cluster state defined in branch \e[1m$SXCM_GIT_BRANCH\e[0m \e[31mdoesn't exist\e[0m. Could not export \e[1m$cn\e[0m"
        exit;
    fi
    cd $CLUSTER_CONFDIR  &> /dev/null
    git add . .* &> /dev/null
    git commit -m "[$cn] Export the $cn cluster state" &> /dev/null
    git push origin $cn
    cd - &> /dev/null
    echo -e "  \e[1m\e[32mExport\e[0m of \e[1m$cn\e[0m cluster is \e[34mdone\e[0m"
}

# info on cluster configuration
function doClusterConfigurationInfo {
    local NAME=${1,,}
    local cn=`getActiveCluster`
    if [[ `getActiveCluster` != $NAME &&  "" != $NAME ]]
    then
        local LIST=$(getClusterConfigurationList)
        for cluster in $LIST
        do
            if [[ $cluster == $NAME ]]; then
                cn=$NAME
            fi
        done
    else 
        cn=`getActiveCluster`
    fi
    if [[ $cn == '' ]]; then
        echo -e "You must give a \e[1mcluster configuration name\e[0m"
        echo -e "You can create one using \e[90;4msxcm create mycluster\e[0m" ;
        echo -e "or get a list of available cluster configuration with \e[90;4msxcm list\e[0m" ;
        exit 1;
    fi
    local clusterConfDir=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    if [[ -r $clusterConfDir/$SXCM_USER_CONF_FILE ]]; then
        echo -e "\e[34mInformation\e[0m on cluster \e[1m$cn\e[0m found in $clusterConfDir/$SXCM_USER_CONF_FILE"
        . $clusterConfDir/$SXCM_USER_CONF_FILE;
        local sourceConfFile=$SXCM_PROFILES_PATH/install-config-$PROFILE.yml
        local desc=$(getClusterDescription $sourceConfFile desc)
        local service=$(getClusterDescription $sourceConfFile service)
        local hourlyCost=$(getClusterHourlyCost $sourceConfFile)
        local admpwd=""
        if [[ -r $clusterConfDir/auth/kubeadmin-password ]]; then
            admpwd=$(cat $clusterConfDir/auth/kubeadmin-password)
        fi
        local STATE=""
        if [[ -r $clusterConfDir/metadata.json || -r $clusterConfDir/terraform.tfstate ]]
        then
            if [[ -r $clusterConfDir/deployed ]]
            then
                STATE="\e[32mdeployed\e[0m"
            else
                STATE="\e[33mdeploying\e[0m"
            fi
        elif [[ -r $clusterConfDir/install-config.yaml ]]
        then
            STATE="\e[36mconfigured\e[0m"
        else
            STATE="\e[34mdefined\e[0m"
        fi
        printf "\e[1m%-10s\e[0m %s\n" name $cn
        printf "\e[1m%-10s\e[0m %s\n" profile $PROFILE
        printf "\e[1m%-10s\e[0m %s$STATE\n" state ""
        printf "\e[1m%-10s\e[0m%s\n" desc "$desc"
        printf "\e[1m%-10s\e[0m%s\n" services "$service"
        printf "\e[1m%-10s\e[0m%s\n" cost " $hourlyCost €/h"
        printf "\e[1m%-10s\e[0m %s\n" "git repo" "$SXCM_GIT_REPO"
        printf "\e[1m%-10s\e[0m %s\n" "git branch" "$SXCM_GIT_BRANCH"
        printf "\e[1m%-10s\e[0m %s\n" "adm user" "kubeadmin"
        printf "\e[1m%-10s\e[0m %s\n" "adm pwd" "$admpwd"
        exit 0;
    else
        echo -e "Cluster configuration named \e[1m$cn\e[0m in $clusterConfDir doesn't exist"
        echo -e "You can create one using \e[90;4msxcm create $cn\e[0m" ;
        exit 3;
    fi
}

# edit cluster configuration
function doClusterConfigurationEdit {
    local NAME=${1,,}
    local cn=`getActiveCluster`
    if [[ `getActiveCluster` != $NAME &&  "" != $NAME ]]
    then
        local LIST=$(getClusterConfigurationList)
        for cluster in $LIST
        do
            if [[ $cluster == $NAME ]]; then
                cn=$NAME
            fi
        done
    else 
        cn=`getActiveCluster`
    fi
    local CLUSTER_CONFDIR=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    if [[ $cn == '' ]]; then
        echo -e "You must give a \e[1mcluster configuration name\e[0m"
        echo -e "You can create one using \e[90;4msxcm create mycluster\e[0m" ;
        echo -e "or get a list of available cluster configuration with \e[90;4msxcm list\e[0m" ;
        exit 1;
    fi
    if [[ ! -w $CLUSTER_CONFDIR/install-config.yaml ]]; then
        echo -e "Cluster configuration named \e[1m$cn\e[0m in $CLUSTER_CONFDIR/install-config.yaml doesn't exist or is not writable"
        echo -e "You can create one using \e[90;4msxcm create $cn\e[0m" ;
        exit 2;
    else
        if [[ -r $CLUSTER_CONFDIR/metadata.json || -r $CLUSTER_CONFDIR/terraform.tfstate ]]; then
            echo -e "Could not edit because cluster is already deployed"
            echo -e "you should run \e[90;4msxcm destroy $cn\e[0m before"
            exit 21;
        fi
        if [[ -r $CLUSTER_CONFDIR/install-config.yaml ]]; then
            cp $CLUSTER_CONFDIR/install-config.yaml $CLUSTER_CONFDIR/install-config.yaml.back
            vi $CLUSTER_CONFDIR/install-config.yaml
            echo -e "Cluster configuration \e[1m$cn\e[0m \e[36mupdated\e[0m "
        else
            echo -e "Cluster configuration named \e[1m$cn\e[0m in $CLUSTER_CONFDIR/install-config.yaml doesn't exist"
            echo -e "You can create one using \e[90;4msxcm create $cn\e[0m" ;
            exit 22;
        fi
    fi
}

# update cluster configuration
function doClusterConfigurationUpdate {
    local NAME=${1,,}
    local cn=`getActiveCluster`
    if [[ `getActiveCluster` != $NAME &&  "" != $NAME ]]
    then
        local LIST=$(getClusterConfigurationList)
        for cluster in $LIST
        do
            if [[ $cluster == $NAME ]]; then
                cn=$NAME
            fi
        done
    else 
        cn=`getActiveCluster`
    fi
    local CLUSTER_CONFDIR=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    if [[ $cn == '' ]]; then
        echo -e "You must give a \e[1mcluster configuration name\e[0m"
        echo -e "You can create one using \e[90;4msxcm create mycluster\e[0m" ;
        echo -e "or get a list of available cluster configuration with \e[90;4msxcm list\e[0m" ;
        exit 1;
    fi
    if [[ -r $CLUSTER_CONFDIR/metadata.json || -r $CLUSTER_CONFDIR/terraform.tfstate ]]; then
        updateClusterResources $cn
        echo -e "Cluster configuration \e[1m$cn\e[0m \e[36mupdated\e[0m "
    else
        echo -e "Cluster configuration named \e[1m$cn\e[0m is not deployed"
        echo -e "You can deploy it using \e[90;4msxcm deploy $cn\e[0m" ;
        exit 22;
    fi
}

# delete cluster configuration
function doClusterConfigurationDelete {
    local NAME=${1,,}
    local cn=`getActiveCluster`
    if [[ `getActiveCluster` != $NAME &&  "" != $NAME ]]
    then
        local LIST=$(getClusterConfigurationList)
        for cluster in $LIST
        do
            if [[ $cluster == $NAME ]]; then
                cn=$NAME
            fi
        done
    else 
        cn=`getActiveCluster`
    fi
    local CLUSTER_CONFDIR=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    echo $CLUSTER_CONFDIR
    if [[ $cn == '' ]]; then
        echo -e "You must give a \e[1mcluster configuration name\e[0m"
        echo -e "You can create one using \e[90;4msxcm create mycluster\e[0m" ;
        echo -e "or get a list of available cluster configuration with \e[90;4msxcm list\e[0m" ;
        return 1;
    fi
    if [[ ! -w $CLUSTER_CONFDIR/install-config.yaml && ! -w $CLUSTER_CONFDIR/install-config.yaml.back ]]; then
        echo -e "Cluster configuration named \e[1m$cn\e[0m doesn't exist or is not writable"
        echo -e "You can create one using \e[90;4msxcm create $cn\e[0m" ;
        return 2;
    else
        if [[ -r $CLUSTER_CONFDIR/metadata.json || -r $CLUSTER_CONFDIR/terraform.tfstate ]]; then
            echo -e "\e[1m$cn\e[0m cluster configuration already \e[36mdeployed\e[0m"
            echo -e "You must destroy it first with \e[90;4msxcm destroy $cn\e[0m" ;
        else
            rm -rf $CLUSTER_CONFDIR
            echo -e "Cluster configuration \e[1m$cn\e[0m \e[31mdeleted\e[0m "
            if [[ $cn == `getActiveCluster` ]]; then
                local LIST=$(getClusterConfigurationList)
                local COUNT=$(echo $LIST | wc -w)
                if [[ $COUNT -gt 0 ]]; then
                    for cluster in $LIST
                    do
                        setActiveCluster $cluster
                    done
                else
                    setActiveCluster ""
                fi
            fi
        fi
    fi
}

# list cluster configuration
function doClusterConfigurationList {
    local LIST=$(getClusterConfigurationList)
    local COUNT=$(echo $LIST | wc -w)
    local STATE=""
    local cn=$(getActiveCluster)
    local CLUSTER_CONF=""
    local desc=""
    if [[ $COUNT -gt 0 ]]; then
        echo -e "\e[33mList\e[0m \e[1m$COUNT\e[0m cluster configuration in the cluster stack"
        for cluster in $LIST
        do
            if [[ -r $SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cluster/metadata.json || -r $SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cluster/terraform.tfstate ]]
            then
                local URL=$(cat $SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cluster/auth/kubeconfig | grep server | cut -d: -f2-10 | xargs)
                if [[ -r $SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cluster/deployed ]]
                then
                    STATE="\e[32m(deployed)  \e[0m - $URL"
                else
                    STATE="\e[33m(deploying) \e[0m - $URL"
                fi
                CLUSTER_CONF=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cluster/install-config.yaml.back
            elif [[ -r $SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cluster/install-config.yaml ]]
            then
                CLUSTER_CONF=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cluster/install-config.yaml
                STATE="\e[36m(configured)\e[0m"
            else
                CLUSTER_CONF=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cluster/install-config.yaml.back
                STATE="\e[34m(defined)   \e[0m"
            fi
            if [[ -r $SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cluster/$SXCM_USER_CONF_FILE ]]; then
                . $SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cluster/$SXCM_USER_CONF_FILE;
                export SXCM_CLUSTER_NAME=$(getActiveCluster);
            fi
            desc=$(getClusterDescription $CLUSTER_CONF)
            if [[ $cluster == $SXCM_CLUSTER_NAME ]]; then
                printf "\e[1mx %-14s\e[0m $STATE %s\n" $cluster "$desc"
            else
                printf "  %-14s $STATE %s\n" $cluster "$desc"
            fi
            desc=""
        done
    else
        echo -e "\e[1mNo\e[0m cluster configuration found in the cluster stack"
        echo -e "You can create one using \e[90;4msxcm create mycluster\e[0m" ;
    fi
}

# change active cluster
function doClusterDisplayActive {
    local cn=$(getActiveCluster)
    if [[ "" == $cn ]]; then
        echo -e "\e[31mNo\e[0m cluster configuration is set as \e[32mactive\e[0m cluster configuration"
    else
        echo -e "\e[1m$cn\e[0m cluster configuration is set as the \e[32mactive\e[0m cluster"
    fi
}

# change active cluster
function doClusterChangeActive {
    local NAME=$1
    local LIST=$(getClusterConfigurationList)
    if [[ "" == $NAME ]]; then
        echo -e "\eYou must give a cluster name to set as the active cluster"
        echo -e "You can create a cluster using \e[90;4msxcm create mycluster\e[0m" ;
        echo -e "or list available cluster configuration by running \e[90;4msxcm list\e[0m" ;
        return 1;
    else
        for cluster in $LIST
        do
            if [[ $cluster == $NAME ]]; then
                echo -e "Set \e[32mactive\e[0m cluster configuration to \e[1m$NAME\e[0m"
                setActiveCluster $NAME
                return 0;
            fi
        done
    fi
    echo -e "\e[1m$NAME\e[0m cluster configuration not found in the cluster stack"
    echo -e "You can create it using \e[90;4msxcm create mycluster\e[0m" ;
    echo -e "or list available cluster configuration by running \e[90;4msxcm list\e[0m" ;
    return 1;
}

# deploy given cluster
function doClusterDeploy {
    local NAME=${1,,}
    local cn=`getActiveCluster`
    if [[ `getActiveCluster` != $NAME &&  "" != $NAME ]]
    then
        local LIST=$(getClusterConfigurationList)
        for cluster in $LIST
        do
            if [[ $cluster == $NAME ]]; then
                cn=$NAME
            fi
        done
    else 
        cn=`getActiveCluster`
    fi
    local CLUSTER_CONFDIR=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    if [[ -r $CLUSTER_CONFDIR/metadata.json || -r $CLUSTER_CONFDIR/terraform.tfstate ]]; then
        echo -e "\e[1m$cn\e[0m cluster configuration already \e[36mdeployed\e[0m"
        cd $CLUSTER_CONFDIR &> /dev/null
        git checkout $cn &> /dev/null
        createClusterResources $cn
        git add . &> /dev/null
        git commit -m "[$cn] Configuration day-two of the $cn cluster" &> /dev/null
        git push origin $cn
        cd - &> /dev/null
        echo -e "You can refresh connection by running \e[90;4msxcm connect $cn\e[0m" ;
        echo -e "or destroy this cluster with \e[90;4msxcm destroy $cn\e[0m" ;
    else
        installClusterInstallerIfNotPresent
        echo -e "Start \e[1m$cn\e[0m cluster deployment based on \e[1mopenshift $SXCM_OCPI_RELEASE\e[0m"
        cat $CLUSTER_CONFDIR/install-config.yaml > $CLUSTER_CONFDIR/install-config.yaml.back
        cd $CLUSTER_CONFDIR &> /dev/null
        openshift-install create cluster
        touch $CLUSTER_CONFDIR/deployed
        echo -e "Cluster \e[1m$cn\e[0m \e[36mdeployed\e[0m"
        git checkout $cn &> /dev/null
        git add . &> /dev/null
        git commit -m "[$cn] Configuration post-deployment of the $cn cluster" &> /dev/null
        git push origin $cn
        createClusterResources $cn
        git add . &> /dev/null
        git commit -m "[$cn] Configuration day-two of the $cn cluster" &> /dev/null
        git push origin $cn
        cd - &> /dev/null
        echo -e "Cluster \e[1m$cn\e[0m \e[36mconfigured\e[0m"
    fi
}

# deploy active cluster
function doClusterDeployActive {
    doClusterDeploy `getActiveCluster`
}

# destroy given cluster
function doClusterDestroy {
    local NAME=${1,,}
    local cn=`getActiveCluster`
    if [[ `getActiveCluster` != $NAME &&  "" != $NAME ]]
    then
        local LIST=$(getClusterConfigurationList)
        for cluster in $LIST
        do
            if [[ $cluster == $NAME ]]; then
                cn=$NAME
            fi
        done
    else 
        cn=`getActiveCluster`
    fi
    local CLUSTER_CONFDIR=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    if [[ -r $CLUSTER_CONFDIR/metadata.json ]]; then
        echo -en "Do you want to \e[31mdestroy\e[0m cluster $cn [y/N] : "
        read doDestroy
        if [[ "$doDestroy" == "y" ]]; then
            installClusterInstallerIfNotPresent
            echo -e "Start \e[1m$cn\e[0m cluster \e[31mdestruction\e[0m"
            cd $CLUSTER_CONFDIR &> /dev/null
            git checkout $cn &> /dev/null
            git add . &> /dev/null
            git commit -m "[$cn] Record state just before destruction of the $cn cluster" &> /dev/null
            openshift-install destroy cluster
            git add . &> /dev/null
            git commit -m "[$cn] Record state just after destruction of the $cn cluster" &> /dev/null
            cat $CLUSTER_CONFDIR/install-config.yaml.back > $CLUSTER_CONFDIR/install-config.yaml
            rm $CLUSTER_CONFDIR/install-config.yaml.back $CLUSTER_CONFDIR/terraform.* $CLUSTER_CONFDIR/meta* $CLUSTER_CONFDIR/deployed &> /dev/null
            git add . &> /dev/null
            git commit -m "[$cn] Record state after post-destruction actions of the $cn cluster" &> /dev/null
            git push origin $cn
            cd - &> /dev/null
            echo -e "Cluster \e[1m$cn\e[0m \e[31mdestroyed\e[0m"
        else
            exit;
        fi
    else
        echo -e "\e[1m$cn\e[0m cluster configuration doesn't have metadata.json and terraform.tfstate files"
        echo -e "You can create it using \e[90;4msxcm deploy $cn\e[0m" ;
    fi
}

# destroy active cluster
function doClusterDestroyActive {
    doClusterDestroy `getActiveCluster`
}

# connect given cluster
function doClusterConnect {
    local NAME=$1
    if [[ "" == $NAME ]]
    then
        echo -e "\eYou must give a cluster name or set an active one"
        echo -e "You can create a cluster using \e[90;4msxcm create mycluster\e[0m" ;
        echo -e "or list available cluster configuration by running \e[90;4msxcm list\e[0m" ;
        echo -e "and set one as active with \e[90;4msxcm switch mycluster\e[0m" ;
        return 1;
    elif [[ `getActiveCluster` != $NAME ]]
    then
        local LIST=$(getClusterConfigurationList)
        for cluster in $LIST
        do
            if [[ $cluster == $NAME ]]; then
                echo -e "Set \e[1mactive cluster\e[0m configuration to \e[1m$NAME\e[0m"
                setActiveCluster $NAME
            fi
        done
    fi
    local cn=`getActiveCluster`
    local CLUSTER_CONFDIR=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    if [[ -r $CLUSTER_CONFDIR/metadata.json && -r $CLUSTER_CONFDIR/terraform.tfstate ]]; then
        recordAdminTokenFromCreatedCluster $cn
        echo -e "\e[31mconnected\e[0m to cluster \e[1m$cn\e[0m "
    else
        echo -e "\e[1m$cn\e[0m cluster configuration doesn't have metadata.json and terraform.tfstate files"
        echo -e "You can create it using \e[90;4msxcm deploy $cn\e[0m" ;
    fi
}

# connect active cluster
function doClusterConnectActive {
    doClusterConnect `getActiveCluster`
}

# sub-menu for create command
function menuClusterCreate {
    if [[ "$1" == "init"  && "$2" == "" ]]; then
        menuHeadArt
            cat <<EOF

sxcm init sub-command for initialize a sxcm managed cluster stored into the managed cluster stack

Usage:
sxcm init NAME

Examples:
# Initialize a cluster named mycluster
sxcm init mycluster

EOF
    elif [[ -z "$2" || "$2" == "" ]]; then
        menuHeadArt
            cat <<EOF

sxcm create sub-command for creating a sxcm managed cluster by adding a new cluster configuration to the managed cluster stack

Usage:
sxcm create NAME PROFILE

Examples:
# Create a cluster named mycluster using the default profile
sxcm create mycluster

# Create a cluster named mycluster using the small profile
sxcm create mycluster small

If you want to have a list of availables cluster profiles,
you can run :
$ sxcm profiles

EOF
    else
        doClusterConfigurationCreate $2 $3
    fi
}

# sub-menu for import command
function menuClusterImport {
    if [[ -z "$1" || "$1" == "" ]]; then
        menuHeadArt
            cat <<EOF

sxcm import sub-command for importing a sxcm managed cluster. It will create a local cluster configuration 
based on a remote cluster repository

Usage:
sxcm import NAME [BRANCH]

Examples:
# Import the cluster named mycluster using the cluster git repository configuration
sxcm import mycluster
# Import the cluster named mycluster using the myclusterbranch branch stored into the cluster git repository
sxcm import mycluster myclusterbranch

EOF
    else
        doClusterConfigurationImport $1 $2
    fi
}


# sub-menu for export command
function menuClusterExport {
    if [[ -z "$1" || "$1" == "" ]]; then
        doClusterConfigurationExport `getActiveCluster`
    else
        doClusterConfigurationExport $1
    fi
}

# sub-menu for info command
function menuClusterInfo {
    if [[ -z "$1" || "$1" == "" ]]; then
        doClusterConfigurationInfo `getActiveCluster`
    else
        doClusterConfigurationInfo $1
    fi
}

# sub-menu for edit command
function menuClusterEdit {
    if [[ -z "$1" || "$1" == "" ]]; then
        doClusterConfigurationEdit `getActiveCluster`
    else
        doClusterConfigurationEdit $1
    fi
}

# sub-menu for update command
function menuClusterUpdate {
    if [[ -z "$1" || "$1" == "" ]]; then
        doClusterConfigurationUpdate `getActiveCluster`
    else
        doClusterConfigurationUpdate $1
    fi
}

# sub-menu for delete command
function menuClusterDelete {
    if [[ -z "$1" || "$1" == "" ]]; then
        doClusterConfigurationDelete `getActiveCluster`
    else
        doClusterConfigurationDelete $1
    fi
}

# sub-menu for list command
function menuClusterList {
    doClusterConfigurationList
}

# sub-menu for current command
function menuClusterCurrent {
    if [[ -z "$1" || "$1" == "" ]]; then
        doClusterDisplayActive
    else
        doClusterChangeActive $1
    fi
}

# sub-menu for deploy command
function menuClusterDeploy {
    if [[ -z "$1" || "$1" == "" ]]; then
        doClusterDeployActive
    else
        doClusterDeploy $1
    fi
}

# sub-menu for destroy command
function menuClusterDestroy {
    if [[ -z "$1" || "$1" == "" ]]; then
        doClusterDestroyActive
    else
        doClusterDestroy $1
    fi
}

# sub-menu for connect command
function menuClusterConnect {
    if [[ -z "$1" || "$1" == "" ]]; then
        doClusterConnectActive
    else
        doClusterConnect $1
    fi
}

# main menu for the cluster sub-command
function menuCluster {
    case $1 in
        create|init)    menuClusterCreate ${1} ${2} ${3};;
        info)           menuClusterInfo ${2};;
        edit)           menuClusterEdit ${2};;
        update)         menuClusterUpdate ${2};;
        delete)         menuClusterDelete ${2};;
        list)           menuClusterList;;
        current|switch) menuClusterCurrent ${2};;
        deploy)         menuClusterDeploy ${2};;
        destroy)        menuClusterDestroy ${2};;
        connect|login)  menuClusterConnect ${2};;
        import)         menuClusterImport ${2} ${3};;
        export)         menuClusterExport ${2};;
        *)              menuUsage;;
    esac
}
