#!/bin/bash

# demos demo
function doListDemos {
    echo -e "\e[33mList\e[0m \e[1mavailables demos\e[0m"
    doListDemosAbstract "false"
}

# demos demo generator for both local or shared
function doListDemosAbstract {
    local LIST
    local LISTRead=()
    local TITLE=shared
    local ECHOTITLE=true
    local filepath=""
    local democontent=""
    local desc=""
    LIST=$(listDemosDefault)
    TITLE=shared
    if [[ $1 == "false" ]]; then
        ECHOTITLE=false
    fi
    local LISTOutput=($(constructDemosList "${LIST[@]}" "${LISTRead[@]}"))
    COUNT=${#LISTOutput[@]}
    if [[ $ECHOTITLE == "true" ]]; then
        echo -e "\e[33mList\e[0m \e[1m$COUNT\e[0m availables \e[0m$TITLE\e[0m demos"
    fi
    for demo in "${LISTOutput[@]}"; do
        filepath=$SXCM_DEMOS_PATH/$demo
        type=none
        if [[ -d $filepath ]]; then
            democontent="$(ls $filepath/*.yml 2>/dev/null | wc -l) yaml, $(ls $filepath/*.sh 2>/dev/null | wc -l) bash"
            type="directory ($democontent)"
        else
            type="file (yaml)"
        fi
        printf "\e[1m%-20s\e[0m %s\n" $demo "$type"
        desc=""
    done
}

# construct a list of demos
function constructDemosList {
    local LISTin=$1
    local LISTout=$2
    local COUNT=${#LISTin[@]}
    for i in "${!LISTin[@]}"; do
        local newdemo=${LISTin[i]}
        local isFound=false
        for j in "${!LISTout[@]}"; do
            local recordeddemo=${LISTout[j]}
            if [[ $newdemo = $recordeddemo ]]; then
                isFound=true
            fi
        done
        if [[ $isFound == "false" ]]; then
            LISTout+=("$newdemo")
        fi
    done
    for i in "${!LISTout[@]}"; do
        echo "${LISTout[i]}"
    done
}

# get list of default demos
function listDemosDefault {
    echo $(listDemos $SXCM_DEMOS_PATH)
}

# get list of cluster demos
function listDemosCluster {
    local cn=$1
    local demoDirLocal=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn/$SXCM_USER_CONF_DIR_DEMOS
    echo $(listDemos $demoDirLocal)
}

# get list cluster configuration
function listDemos {
    local path=${1}
    local LIST=$(ls $path 2>/dev/null)
    local COUNT=$(echo $LIST | wc -w)
    if [[ $COUNT -gt 0 ]]; then
        for demo in $LIST; do
            filename=${demo#"$path/"}
            filename=${filename%".yml"}
            echo "${filename}"
        done
    fi
}

# create demos
function applyClusterDemo {
    local UPSERT=$1
    local cn=$2
    local rn=$3
    local clusterConfOCPInstallFile=$(getOCPInstallFileForCluster $cn)
    local localEnv=${SXCM_ENV:-dev}
    local localVersion=${SXCM_VERSION:-beta}
    local localScope=${SXCM_CLUSTER_SCOPE:-scope}
    local clusterConfDir=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    local clusterConfDirDemo=$clusterConfDir/$SXCM_USER_CONF_DIR_DEMOS
    local clusterRegion=$(extractOCPInstallAWSRegion $clusterConfOCPInstallFile)
    local clusterProfile=$(extractOCPInstallProfile $clusterConfOCPInstallFile)
    local clusterID=$(oc get machineset -n openshift-machine-api -o jsonpath="{.items[0].metadata.labels}" | cut -d \" -f 4)
    local clusterK8s=$(echo $SXCM_CLUSTER_URL | sed -e 's|https://||g')
    clusterK8s=$(echo $clusterK8s | sed -e 's|\.|-|g')
    local CLUSTERTIMEOUT=5
    local CMD="oc apply $SXCM_OCAPPLY_OPTS --cluster=$clusterK8s -f -"
    if [[ $UPSERT == "delete" ]]
    then
        CMD="oc delete --wait=false -f -"
    fi
    local LIST=$(ls $clusterConfDirDemo/$rn 2>/dev/null)
    local COUNT=$(echo $LIST | wc -w)
    if [[ $COUNT -gt 0 ]]; then
        for demo in $LIST; do
            local file="$clusterConfDirDemo/$rn/${demo}"
            local CLUSTERTIMEOUT=4
            local filename=${demo#"$clusterConfDirDemo/$rn/"}; filename=${filename%"/"}
            local oldifs="$IFS"; IFS="-"; tab=($filename); IFS="$oldifs"
            local FAMILLY="${tab[0]}"
            # 1x. Admin template without params
            # 2x. Admin template with default, rhn and aws params
            # 3x. Admin template with default params and script enabled
            # 4x. Admin template (reserved)
            # 5x. Admin template (reserved)
            # 6x. Developer template without params
            # 7x. Developer template with default, rhn and aws params
            # 8x. Developer template with default params and script enabled
            # 9x. Developer template (reserved)
            if [[ -x $file ]]
            then
                if [[ $filename != "sxcm-demo.sh" ]]
                then
                    echo -e "${UPSERT} \e[1m$rn\e[0m \e[1mdemo\e[0m in cluster \e[1m$cn\e[0m from file \e[1m${demo}\e[0m \e[93m(admin)\e[0m"
                    . $file $UPSERT "$cn" "$localScope" "$localEnv" "$localVersion" "$cn" "$clusterK8s" "$SXCM_DOCKER_LOGIN:$SXCM_DOCKER_PWD" "$SXCM_QUAYIO_LOGIN:$SXCM_QUAYIO_PWD"
                fi
            else
                if [[ "${file: -3}" == ".sh" ]]
                then
                echo -e "${UPSERT} \e[1m$rn\e[0m \e[1mdemo\e[0m in cluster \e[1m$cn\e[0m from file \e[1m${demo}\e[0m skipped"
                else
                    echo -e "${UPSERT} \e[1m$rn\e[0m \e[1mdemo\e[0m in cluster \e[1m$cn\e[0m from file \e[1m${demo}\e[0m \e[93m(admin)\e[0m"
                    if [[ "${FAMILLY:0:1}" == "2" ]]
                    then
                        oc process -f $file --local -o yaml \
                        -p SCOPE=$localScope \
                        -p CLUSTER=$cn \
                        -p ENV=$localEnv \
                        -p VERSION=$localVersion \
                        -p DOCKERHUB_LOGIN=$SXCM_DOCKER_LOGIN \
                        -p DOCKERHUB_PWD=$SXCM_DOCKER_PWD \
                        -p QUAYIO_LOGIN=$SXCM_QUAYIO_LOGIN \
                        -p QUAYIO_PWD=$SXCM_QUAYIO_PWD \
                        -p RHN_USER=$SXCM_RHN_USER \
                        -p RHN_PASSWORD=$SXCM_RHN_PASSWORD \
                        | $CMD
                    elif [[ "${FAMILLY:0:1}" == "4" ]]
                    then
                        # -p AWS_SMTP_USER=$SXCM_AWS_SMTP_USER \
                        # -p AWS_SMTP_PASSWORD=$SXCM_AWS_SMTP_PASSWORD \
                        # -p AWS_SMTP_ZONE=$SXCM_AWS_SMTPZONE \
                        # -p AWS_SMTP_FROM=$SXCM_AWS_SMTPFROM \
                        oc process -f $file --local -o yaml \
                        -p SCOPE=$localScope \
                        -p CLUSTER=$cn \
                        -p ENV=$SXCM_ENV \
                        -p VERSION=$localVersion \
                        -p AWS_ZONE=$SXCM_AWS_ZONE \
                        -p AWS_ACCESS_ID=$SXCM_AWS_ID \
                        -p AWS_ACCESS_KEY=$SXCM_AWS_KEY \
                        | $CMD
                    elif [[ "${FAMILLY:0:1}" == "5" ]]
                    then
                        oc process -f $file --local -o yaml \
                        -p SCOPE=$localScope \
                        -p CLUSTER=$cn \
                        -p ENV=$localEnv \
                        -p VERSION=$localVersion \
                        -p CLUSTERID=$clusterID \
                        -p CLUSTER_REGION=$clusterRegion \
                        -p RHN_USER=$SXCM_RHN_USER \
                        | $CMD
                    else
                        oc process -f $file --local -o yaml \
                        -p SCOPE=$localScope \
                        -p CLUSTER=$cn \
                        -p ENV=$localEnv \
                        -p VERSION=$localVersion \
                        | $CMD
                    fi
                fi
            fi
            if [[ "${UPSERT}" == "create" ]]; then
                echo -e "wait ${CLUSTERTIMEOUT}sec for deployment dependencies start"
                temporize $CLUSTERTIMEOUT 2
            fi
        done
    fi
}

##################

# edit demo configuration
function doDemoEdit {
    local rn=$1
    local cn=$2
    if [[ "$rn" == "" ]]; then
        echo -en "Which demo do you wan't to use [mydemo] : "
        read rn
        if [[ $rn == '' ]]; then
            rn="mydemo"
        fi
    fi
    if [[ $cn == '' ]]; then
        cn=$(getActiveCluster)
    fi
    reloadIndividualClusterConf $cn
    echo -e "\e[1m\e[33mEditing\e[0m the demo \e[1m$rn\e[0m in cluster \e[1m$cn\e[0m"
    local clusterDir=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    local clusterDemosDir=$clusterDir/$SXCM_USER_CONF_DIR_DEMOS
    local clusterDemoDir=$clusterDemosDir/$rn
    if [[ -d $clusterDemoDir ]]; then
        vi $clusterDemoDir/*
        cd $clusterDir &>/dev/null
        git add . &>/dev/null
        git commit -am "[$cn] Edit the $rn demo defined in the $cn cluster" &>/dev/null
        git push origin $cn &> /dev/null
        cd - &>/dev/null
        echo -e "\e[1m\e[33mUpdated\e[0m demo \e[1m$rn\e[0m in cluster \e[1m$cn\e[0m"
    else
        echo -e "\e[1m\e[31mCould not read\e[0m directory \e[1m$rn\e[0m in $clusterDemosDir"
    fi
}

# update demo configuration
function doDemoUpdate {
    local rn=$1
    local cn=$2
    if [[ "$rn" == "" ]]; then
        echo -en "Which demo do you wan't to use [mydemo] : "
        read rn
        if [[ $rn == '' ]]; then
            rn="mydemo"
        fi
    fi
    if [[ $cn == '' ]]; then
        cn=$(getActiveCluster)
    fi
    reloadIndividualClusterConf $cn
    local clusterDir=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    local clusterDemosDir=$clusterDir/$SXCM_USER_CONF_DIR_DEMOS
    local clusterDemoDir=$clusterDemosDir/$rn
    local demoIsFoundInDemoDir="false"
    local clusterConfOCPInstallFile=$(getOCPInstallFileForCluster $cn)
    local IsDeployed=false
    if [[ ! -d $clusterDir ]]; then
        echo -e "\e[1mNo cluster\e[0m config found at \e[1m$clusterDir\e[0m for enabling the \e[1m$rn\e[0m demos"
    else
        echo -e "\e[1m\e[96mUpdate\e[0m the demo \e[1m$rn\e[0m with the cluster \e[1m$cn\e[0m"
        if [[ -r $clusterDir/metadata.json || -r $clusterDir/terraform.tfstate ]] && [[ -r $clusterDir/deployed ]]
        then
            IsDeployed=true
        fi
        if [[ "$IsDeployed" == "true" ]]
        then
            applyClusterDemo "update" $cn $rn
        else
            echo -e "Could not \e[1mupdate $rn\e[0m demo on cluster \e[1m$cn\e[0m because cluster is \e[1m\e[35mnot deployed\e[0m"
        fi
    fi
}

# information demo configuration
function doDemoInfo {
    local rn=$1
    if [[ "$rn" == "" ]]; then
        echo -en "Which demo do you wan't to use [mydemo] : "
        read rn
        if [[ $rn == '' ]]; then
            rn="mydemo"
        fi
    fi
    echo -e "Title       : \e[1m\e[34mDEMO ${rn^^}\e[0m"
    local demoDirLocal=$SXCM_DEMOS_PATH
    local LIST=$(listClusterConfigs)
    local COUNT=$(echo $LIST | wc -w)
    if [[ -d $demoDirLocal/$rn ]]; then
        local demoScript="$demoDirLocal/$rn/sxcm-demo.sh"
        if [[ -x $demoScript ]]
        then
            . $demoScript info "$rn"
        fi
        echo "Location    : $demoDirLocal/$rn"
        echo "Content     : " "$(ls $demoDirLocal/$rn/*.yml 2>/dev/null | wc -l) yaml, $(ls $demoDirLocal/$rn/*.sh 2>/dev/null | wc -l) bash"
    else
        echo -e "\e[1m\e[31mCould not read\e[0m directory \e[1m$rn\e[0m in $demoDirLocal"
        exit 1
    fi
    if [[ $COUNT -gt 0 ]]; then
        local first="true"
        for cluster in $LIST
        do
            local demoIsFoundInOCPInstall="false"
            local prefix="           "
            for demo in $(listDemosCluster $cluster); do
                if [[ "$demo" == "$rn" ]]; then
                    demoIsFoundInOCPInstall="true"
                fi
            done
            if [[ "$first" == "true" ]]; then
                first="false"
                prefix="Clusters   "
            fi
            if [[ "$demoIsFoundInOCPInstall" == "true" ]]; then
                echo -e "$prefix - \e[1m\e[96menabled\e[0m  in cluster \e[1m$cluster\e[0m"
            else
                echo -e "$prefix - \e[95mdisabled\e[0m in cluster \e[1m$cluster\e[0m"
            fi
        done
    fi
    exit
}

# run demo configuration
function doDemoRun {
    local rn=$1
    local action=$2
    local option=$3
    local cn=$4
    if [[ "$rn" == "" ]]; then
        echo -en "Which demo do you wan't to use [mydemo] : "
        read rn
        if [[ $rn == '' ]]; then
            rn="mydemo"
        fi
    fi
    if [[ $action != 'begin' && $action != 'step' && $action != 'end' ]]; then
        echo -en "Which action do you wan't to perform (begin,step,end) [begin] : "
        read action
        if [[ $action == '' ]]; then
            action="begin"
        fi
    fi
    if [[ $action == 'begin' || $action == 'end' ]]; then
        cn=$option
    fi
    if [[ $action == 'step' && $option == "" ]]; then
        echo -en "Which step do you wan't to reach (1,2,3,...) [1] : "
        read option
        if [[ $option == '' ]]; then
            option="1"
        fi
    fi
    if [[ $cn == '' ]]; then
        cn=$(getActiveCluster)
    fi
    reloadIndividualClusterConf $cn
    local demoIsFoundInDemoDir="false"
    local clusterConfOCPInstallFile=$(getOCPInstallFileForCluster $cn)
    local localEnv=${SXCM_ENV:-dev}
    local localVersion=${SXCM_VERSION:-beta}
    local localScope=${SXCM_CLUSTER_SCOPE:-scope}
    local clusterConfDir=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    local clusterConfDirDemo=$clusterConfDir/$SXCM_USER_CONF_DIR_DEMOS
    local clusterDemoDir=$clusterConfDirDemo/$rn
    local IsDeployed=false
    if [[ ! -d $clusterConfDir ]]; then
        echo -e "\e[1mNo cluster\e[0m config found at \e[1m$clusterConfDir\e[0m for enabling the \e[1m$rn\e[0m demos"
    else
        echo -e "\e[1m\e[96mRun\e[0m the demo \e[1m$rn\e[0m with the cluster \e[1m$cn\e[0m"
        if [[ -r $clusterConfDir/metadata.json || -r $clusterConfDir/terraform.tfstate ]] && [[ -r $clusterConfDir/deployed ]]
        then
            IsDeployed=true
        fi
        if [[ "$IsDeployed" == "true" ]]
        then
            local clusterRegion=$(extractOCPInstallAWSRegion $clusterConfOCPInstallFile)
            local clusterProfile=$(extractOCPInstallProfile $clusterConfOCPInstallFile)
            local clusterID=$(oc get machineset -n openshift-machine-api -o jsonpath="{.items[0].metadata.labels}" | cut -d \" -f 4)
            local clusterK8s=$(echo $SXCM_CLUSTER_URL | sed -e 's|https://||g')
            clusterK8s=$(echo $clusterK8s | sed -e 's|\.|-|g')
            local demoScript="$clusterDemoDir/sxcm-demo.sh"
            if [[ -x $demoScript ]]
            then
                echo -e "${action} \e[1m$rn\e[0m \e[1mdemo\e[0m in cluster \e[1m$cn\e[0m from file \e[1msxcm-demo.sh\e[0m \e[93m(admin)\e[0m"
                . $demoScript $action "$rn" "$cn" "$localScope" "$localEnv" "$localVersion" "$clusterK8s" "$option"
            else
                echo -e "${action} \e[1m$rn\e[0m \e[1mdemo\e[0m in cluster \e[1m$cn\e[0m from file \e[1msxcm-demo.sh\e[0m \e[93m(admin)\e[0m"
            fi
        else
            echo -e "Could not \e[1mrun $rn\e[0m demo on cluster \e[1m$cn\e[0m because cluster is \e[1m\e[35mnot deployed\e[0m"
        fi
    fi
}

# associate demo configuration
function doDemoAssociate {
    local rn=$1
    local cn=$2
    if [[ "$rn" == "" ]]; then
        echo -en "Which demo do you wan't to use [mydemo] : "
        read rn
        if [[ $rn == '' ]]; then
            rn="mydemo"
        fi
    fi
    if [[ $cn == '' ]]; then
        cn=$(getActiveCluster)
    fi
    reloadIndividualClusterConf $cn
    local clusterDir=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    local clusterDemosDir=$clusterDir/$SXCM_USER_CONF_DIR_DEMOS
    local clusterDemoDir=$clusterDemosDir/$rn
    local demoIsFoundInDemoDir="false"
    if [[ ! -d $clusterDir ]]; then
        echo -e "No cluster config found at \e[1m$clusterDir\e[0m for loading the \e[1m$cn\e[0m demos"
    else
        for demo in $(listDemosCluster $cn); do
            if [[ "$demo" == "$rn" ]]; then
                demoIsFoundInDemoDir="true"
            fi
        done
        if [[ "$demoIsFoundInDemoDir" == "false" ]]; then
            echo -e "\e[1m\e[95mAssociate\e[0m the demo \e[1m$rn\e[0m with the cluster \e[1m$cn\e[0m"
            local demoDirShared=$SXCM_DEMOS_PATH
            if [[ -d $demoDirShared/$rn ]]; then
                    mkdir -p $clusterDemoDir &>/dev/null
                    echo -e "\e[1m\e[90mCopy\e[0m demo \e[1m$rn\e[0m to cluster \e[1m$cn\e[0m"
                    cp -r $demoDirShared/$rn/* $clusterDemoDir/ &>/dev/null
                    cd $clusterDir &>/dev/null
                    git add . &>/dev/null
                    git commit -am "[$cn] Associate the $rn demo to the $cn cluster" &>/dev/null
                    git push origin $cn &> /dev/null
                    cd - &>/dev/null
            fi
        else 
            echo -e "demo \e[1m$rn\e[0m already found in cluster \e[1m$cn\e[0m"
        fi
    fi
}

# dissociate demo configuration
function doDemoDissociate {
    local rn=$1
    local cn=$2
    if [[ "$rn" == "" ]]; then
        echo -en "Which demo do you wan't to use [mydemo] : "
        read rn
        if [[ $rn == '' ]]; then
            rn="mydemo"
        fi
    fi
    if [[ $cn == '' ]]; then
        cn=$(getActiveCluster)
    fi
    reloadIndividualClusterConf $cn
    local clusterDir=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    local clusterDemosDir=$clusterDir/$SXCM_USER_CONF_DIR_DEMOS
    local clusterDemoDir=$clusterDemosDir/$rn
    if [[ ! -d $clusterDir ]]; then
        echo -e "\e[1mNo cluster\e[0m config found at \e[1m$clusterDir\e[0m for loading the \e[1m$cn\e[0m demos"
    else
        rm -rf $clusterDemoDir &>/dev/null
        echo -e "\e[1m\e[95mDissociate\e[0m the demo \e[1m$rn\e[0m from the cluster \e[1m$cn\e[0m"
        cd $clusterDir &>/dev/null
        git add . &>/dev/null
        git commit -am "[$cn] Dissociate the $rn demo from the $cn cluster" &>/dev/null
        git push origin $cn &> /dev/null
        cd - &>/dev/null
    fi
}

# enable demo configuration
function doDemoEnable {
    local rn=$1
    local cn=$2
    if [[ "$rn" == "" ]]; then
        echo -en "Which demo do you wan't to use [mydemo] : "
        read rn
        if [[ $rn == '' ]]; then
            rn="mydemo"
        fi
    fi
    if [[ $cn == '' ]]; then
        cn=$(getActiveCluster)
    fi
    reloadIndividualClusterConf $cn
    local clusterDir=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    local clusterDemosDir=$clusterDir/$SXCM_USER_CONF_DIR_DEMOS
    local clusterDemoDir=$clusterDemosDir/$rn
    local demoIsFoundInDemoDir="false"
    local clusterConfOCPInstallFile=$(getOCPInstallFileForCluster $cn)
    local IsDeployed=false
    if [[ ! -d $clusterDir ]]; then
        echo -e "\e[1mNo cluster\e[0m config found at \e[1m$clusterDir\e[0m for enabling the \e[1m$rn\e[0m demos"
    else
        echo -e "\e[1m\e[96mEnable\e[0m the demo \e[1m$rn\e[0m with the cluster \e[1m$cn\e[0m"
        doDemoAssociate $rn $cn
        if [[ -r $clusterDir/metadata.json || -r $clusterDir/terraform.tfstate ]] && [[ -r $clusterDir/deployed ]]
        then
            IsDeployed=true
        fi
        if [[ "$IsDeployed" == "true" ]]
        then
            applyClusterDemo "update" $cn $rn
            cd $clusterDir &>/dev/null
            git add . &>/dev/null
            git commit -am "[$cn] Enable the $rn demo from the $cn cluster" &>/dev/null
            git push origin $cn &> /dev/null
            cd - &>/dev/null
        else
            echo -e "Could not \e[1menable $rn\e[0m demo on cluster \e[1m$cn\e[0m because cluster is \e[1m\e[35mnot deployed\e[0m"
        fi
    fi
}

# disable demo configuration
function doDemoDisable {
    local rn=$1
    local cn=$2
    if [[ "$rn" == "" ]]; then
        echo -en "Which demo do you wan't to use [mydemo] : "
        read rn
        if [[ $rn == '' ]]; then
            rn="mydemo"
        fi
    fi
    if [[ $cn == '' ]]; then
        cn=$(getActiveCluster)
    fi
    reloadIndividualClusterConf $cn
    local clusterDir=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
    local clusterDemosDir=$clusterDir/$SXCM_USER_CONF_DIR_DEMOS
    local clusterDemoDir=$clusterDemosDir/$rn
    local clusterConfOCPInstallFile=$(getOCPInstallFileForCluster $cn)
    local IsDeployed=false
    if [[ ! -r $clusterConfOCPInstallFile ]]; then
        echo -e "No cluster config found at \e[1m$clusterConfOCPInstallFile\e[0m for loading the \e[1m$cn\e[0m demos"
    else
        if [[ -r $clusterDir/metadata.json || -r $clusterDir/terraform.tfstate ]] && [[ -r $clusterDir/deployed ]]
        then
            IsDeployed=true
        fi
        echo -e "\e[1m\e[95mDisable\e[0m the demo \e[1m$rn\e[0m with the cluster \e[1m$cn\e[0m"
        if [[ "$IsDeployed" == "true" ]]
        then
            applyClusterDemo "delete" $cn $rn
        else
            echo -e "Could not \e[1mdisable $rn\e[0m demo on cluster \e[1m$cn\e[0m because cluster is \e[1m\e[35mnot deployed\e[0m"
        fi
        doDemoDissociate $rn $cn
        cd $clusterDir &>/dev/null
        git add . &>/dev/null
        git commit -am "[$cn] Disable the $rn demo from the $cn cluster" &>/dev/null
        git push origin $cn
        cd - &>/dev/null
    fi
}

###################

# sub-menu for update command
function menuDemoUpdate {
    isPametersContainHelpers $1 $2 $3 $4
    if [[ $? == "0" || "$1" == "" ]]; then
        menuHeadArt
        cat <<EOF

sxcm demo update sub-command to update a demo into the running cluster

# Usage

[user@localhost]$ sxcm demo update DEMONAME [CLUSTERNAME]


# Examples

# Update the mydemo demo in the currently active cluster
sxcm demo update mydemo
# Update the mydemo demo in the mycluster cluster
sxcm demo update mydemo mycluster


EOF
    else
        doDemoUpdate $1 $2
    fi
}

# sub-menu for run command
function menuDemoRun {
    isPametersContainHelpers $1 $2 $3 $4 $5
    if [[ $? == "0" || "$1" == "" ]]; then
        menuHeadArt
        cat <<EOF

sxcm demo run sub-command to run a demo into the given cluster (default is active cluster)

# Usage

[user@localhost]$ sxcm demo run DEMONAME [CLUSTERNAME]


# Examples

# Run the mydemo demo in the currently active cluster
sxcm demo run mydemo
# Start to run the mydemo demo in the currently active cluster
sxcm demo run mydemo start
# Start to run the mydemo demo in the mycluster cluster
sxcm demo run mydemo start mycluster
# Run the mydemo demo in the mycluster cluster
sxcm demo run mydemo mycluster


EOF
    else
        doDemoRun $1 $2 $3 $4
    fi
}

# sub-menu for info command
function menuDemoInfo {
    isPametersContainHelpers $1 $2 $3 $4
    if [[ $? == "0" || "$1" == "" ]]; then
        menuHeadArt
        cat <<EOF

sxcm demo info sub-command to read detail from a demo stored into the local demo stack

# Usage

[user@localhost]$ sxcm demo info DEMONAME


# Examples

# Read a demo info from the local demo stack
sxcm demo info mydemo

EOF
    else
        doDemoInfo $1 $2
    fi
}

# sub-menu for edit command
function menuDemoEdit {
    isPametersContainHelpers $1 $2 $3 $4
    if [[ $? == "0" || "$1" == "" ]]; then
        menuHeadArt
        cat <<EOF

sxcm demo edit sub-command to change content of a demo stored into the local demo stack

# Usage

[user@localhost]$ sxcm demo edit DEMONAME


# Examples

# Start editor on mycluster demo and record change into the local demo stack
sxcm demo edit mydemo

EOF
    else
        doDemoEdit $1 $2
    fi
}

# sub-menu for associate command
function menuDemoAssociate {
    isPametersContainHelpers $1 $2 $3 $4
    if [[ $? == "0" || "$1" == "" ]]; then
        menuHeadArt
        cat <<EOF

sxcm demo associate sub-command to add a demo into a cluster configuration

# Usage

[user@localhost]$ sxcm demo associate DEMONAME [CLUSTERNAME]


# Examples

# Associate the mydemo demo with the currently active cluster
sxcm demo associate mydemo
# Associate the mydemo demo with the mycluster cluster
sxcm demo associate mydemo mycluster

EOF
    else
        doDemoAssociate $1 $2
    fi
}

# sub-menu for dissociate command
function menuDemoDissociate {
    isPametersContainHelpers $1 $2 $3 $4
    if [[ $? == "0" || "$1" == "" ]]; then
        menuHeadArt
        cat <<EOF

sxcm demo dissociate sub-command to remove a demo into a cluster configuration

# Usage

[user@localhost]$ sxcm demo dissociate DEMONAME [CLUSTERNAME]


# Examples

# Dissociate the mydemo demo with the currently active cluster
sxcm demo dissociate mydemo
# Dissociate the mydemo demo with the mycluster cluster
sxcm demo dissociate mydemo mycluster

EOF
    else
        doDemoDissociate $1 $2
    fi
}

# sub-menu for enable command
function menuDemoEnable {
    isPametersContainHelpers $1 $2 $3 $4
    if [[ $? == "0" || "$1" == "" ]]; then
        menuHeadArt
        cat <<EOF

sxcm demo enable sub-command to add a demo into a cluster configuration and the running cluster

# Usage

[user@localhost]$ sxcm demo enable DEMONAME [CLUSTERNAME]


# Examples

# Enable the mydemo demo with the currently active cluster
sxcm demo enable mydemo
# Enable the mydemo demo with the mycluster cluster
sxcm demo enable mydemo mycluster


EOF
    else
        doDemoEnable $1 $2
    fi
}

# sub-menu for disable command
function menuDemoDisable {
    isPametersContainHelpers $1 $2 $3 $4
    if [[ $? == "0" || "$1" == "" ]]; then
        menuHeadArt
        cat <<EOF

sxcm demo disable sub-command to remove a demo into a cluster configuration and the running cluster

# Usage

[user@localhost]$ sxcm demo disable DEMONAME [CLUSTERNAME]


# Examples

# Disable the mydemo demo with the currently active cluster
sxcm demo disable mydemo
# Disable the mydemo demo with the mycluster cluster
sxcm demo disable mydemo mycluster


EOF
    else
        doDemoDisable $1 $2
    fi
}

# menu switch for demo usage command
function menuDemoUsage {
    menuHeadArt
    cat <<EOF

This client helps you manage demos availables and their association with configured clusters

Available actions are : list, create, edit, info, enable, disable, associate, dissociate and delete

# Usage

[user@localhost]$ sxcm demo ACTION [options]

# Availables actions

## Cluster demos commands actions (local) :
  - list                                   List available cluster configurations
  - edit DEMONAME [CLUSTERNAME]            edit a demo (only in cluster)
  - info DEMONAME                          Get information about a demo
  - associate DEMONAME [CLUSTERNAME]       Add a demo into a demo list and record it (default is active cluster)
  - dissociate DEMONAME [CLUSTERNAME]      Remove a demo from a demo list and record deletion (default is active cluster)

## Cluster demos commands actions (remote) :
  - enable DEMONAME [CLUSTERNAME]          Add a demo into a demo list, record, apply to running cluster and record it (default is active cluster)
  - disable DEMONAME [CLUSTERNAME]         Remove a demo from the cluster, record it, remove the demo list and record it (default is active cluster)


# Examples

  sxcm demo list                           # List available cluster configurations
  sxcm demo edit mydemo                    # Edit the mydemo demo stored into the default demo stack
  sxcm demo info mydemo                    # Display info about the mydemo demo stored into the local demo stack
  sxcm demo associate mydemo               # Add the mydemo demo into the demo list of the curently active cluster and record it
  sxcm demo associate mydemo mycluster     # Add the mydemo demo into the mycluster demo list and record it
  sxcm demo dissociate mydemo              # Remove the mydemo demo from the curently active demo list and record deletion
  sxcm demo dissociate mydemo mycluster    # Remove the mydemo demo from the mycluster demo list and record deletion
  sxcm demo enable mydemo                  # Add the mydemo demo into the demo list of the curently active cluster and apply it to the running cluster
  sxcm demo enable mydemo mycluster        # Add the mydemo demo into the mycluster demo list and apply it to the running cluster
  sxcm demo disable mydemo                 # Remove the mydemo demo from the curently active demo list and apply it to the running cluster
  sxcm demo disable mydemo mycluster       # Remove the mydemo demo from the mycluster demo list and apply it to the running cluster

EOF

    exit
}

# sub-menu for demos command
function menuDemos {
    isPametersContainHelpers $1 $2
    if [[ $? == "0" || "$1" != "" || "$2" != "" ]]; then
        menuDemoUsage
    else
        doListDemos
    fi
}

# main menu for the cluster sub-command
function menuDemo {
    case $1 in
    info) menuDemoInfo ${2} ${3} ${4} ;;
    edit) menuDemoEdit ${2} ${3} ${4} ;;
    update) menuDemoUpdate ${2} ${3} ${4} ;;
    run) menuDemoRun ${2} ${3} ${4} ${5};;
    list) menuDemos ${2} ${3} ${4} ;;
    associate) menuDemoAssociate ${2} ${3} ${4} ;;
    dissociate) menuDemoDissociate ${2} ${3} ${4} ;;
    enable) menuDemoEnable ${2} ${3} ${4} ;;
    disable | delete) menuDemoDisable ${2} ${3} ${4} ;;
    *) menuDemoUsage ;;
    esac
}
