kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: sxcm-demo-hpa-project
  annotations:
    openshift.io/display-name: Demo STARTX - HPA
    openshift.io/documentation-url: https://sxcm.readthedocs.io/en/latest/demo/hpa
    openshift.io/support-url: https://github.com/startxfr/sxcm/issues/new
    openshift.io/generated-by: sxcm
    openshift.io/provider-display-name: STARTX
    description:
      Deployment of sample application using HPA configuration to 
      demonstrate the auto-scaling capacities of an openshift 4 environment
    iconClass: icon-sso
    tags: startx,hpa,demo,dev
  labels:
    template: sxcm-demo-hpa-project
message: |-
  Your demo project ${NS} for HPA technology is now created.

  Scope          : ${SCOPE}
  Environment    : ${ENV}
  Service        : hpa
  Project        : ${NS}

labels:
  template: sxcm-demo-hpa-project
  app.kubernetes.io/managed-by: sxcm
objects:
- kind: Application
  apiVersion: argoproj.io/v1alpha1
  metadata:
    name: demo-hpa-application
    namespace: "${ARGOCD_NS}"
    labels:  &basic_labels
      app.startx.fr/scope: "${SCOPE}"
      app.startx.fr/cluster: "${CLUSTER}"
      app.startx.fr/component: "${NS}"
      app.kubernetes.io/name: "demo-hpa-application-application"
      app.kubernetes.io/part-of: ${NS}
      app.kubernetes.io/version: "${VERSION}"
      app.kubernetes.io/component: "${NS}-project"
    annotations: &basic_annotations
      openshift.io/generated-by: sxcm
    finalizers:
      - resources-finalizer.argocd.argoproj.io
  spec:
    destination:
      namespace: "${NS}"
      server: 'https://kubernetes.default.svc'
    info:
      - name: teammail
        value: dev@startx.fr
    project: "${NS}"
    source:
      path: charts/example-php/
      repoURL: 'https://github.com/startxfr/helm-repository.git'
      targetRevision: master
      helm:
        valueFiles:
          - values-demo-hpa.yaml
        parameters:
          - name: context.scope
            value: "${SCOPE}"
          - name: context.cluster
            value: "${CLUSTER}"
          - name: context.environment
            value: "${ENV}"
          - name: context.version
            value: "${VERSION}"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=false
        - Validate=true
- kind: HorizontalPodAutoscaler
  apiVersion: autoscaling/v2beta1
  metadata:
    name: ${APP_NAME}
    namespace: "${NS}"
    labels:
      <<: *basic_labels
      app.kubernetes.io/name: "${APP_NAME}-hpa"
    annotations:
      <<: *basic_annotations
  spec:
    scaleTargetRef:
      kind: Deployment
      name: ${APP_NAME}
      apiVersion: apps/v1
    minReplicas: 2
    maxReplicas: 5
    metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 50
parameters:
  - name: NS
    displayName: The namespace where objects goes to
    description: "Namespace to place objects to"
    value: demo-hpa
    required: true
  - name: ARGOCD_NS
    displayName: The namespace where argocd server goes to
    description: "Namespace to place argocd server to"
    value: startx-argocd
    required: true
  - name: APP_NAME
    displayName: Application name
    description: The name of the created application
    value: hpa-app
    required: true
  - name: SCOPE
    displayName: Project scope
    description: "Project scope (ex: demo)"
    value: demo
    required: true
  - name: CLUSTER
    displayName: Cluster name
    description: "Name of the current cluster  (ex: sxsf)"
    value: sxsf
    required: true
  - name: ENV
    displayName: Project environment
    description: "Project environment (ex: dev, factory, preprod or prod)"
    value: dev
    required: true
  - name: VERSION
    displayName: Project version
    description: "Project deployed release"
    value: "1.0.0-dev"
    required: true
  - name: COMPONENT
    displayName: Project service
    description: "Project service"
    value: demo
    required: true
