apiVersion: v1
baseDomain: startx.fr
metadata:
  name: __mycluster__
  annotations:
    hourlyCost: "3,54"
    description: "3 master (8Vcpu, 16Go RAM, 200Go io1  1000iop) +  6 worker ( 8Vcpu,  64Go RAM, 200Go io1  1000iop) - [AWS Dublin]"
    descriptionTab: "| 3  | 8  | 16  | 200 | io1 | 1000 | 6  | 8  | 64  | 200 | io1 | 1000 | AWS Dublin"
    descriptionClusterconfig: argocd,pipeline,istio,quaysec,machine,workspaces,couchbase,sso,vault,Knative,logging,RHACM,quay,OCS,metering,3Scale
    clusterconfig: argocd-project,argocd-deploy,infra,auth,rbac,infra,machine,console,storage,ocs,pipeline,istio,knative,3scale,logging,quaysec,couchbase,sso,quay,vault,workspaces,acm,metering
compute:
  - name: worker
    hyperthreading: Enabled
    replicas: 6
    platform:
      aws:
        type: r5a.2xlarge
        zones:
          - eu-west-1a
          - eu-west-1b
          - eu-west-1c
        rootVolume:
          iops: 1000
          size: 200
          type: io1
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      type: c5a.2xlarge
      zones:
        - eu-west-1a
        - eu-west-1b
        - eu-west-1c
      rootVolume:
        iops: 1000
        size: 200
        type: io1
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineCIDR: 10.16.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  aws:
    region: eu-west-1
    userTags:
      project: sxsf
      cluster: __mycluster__
      profile: tera
      environment: test
      projectOwner: chris
pullSecret: '__ocpPullSecret__'
sshKey: |
  __ocpSshPublickey__
