apiVersion: v1
baseDomain: startx.fr
metadata:
  name: __mycluster__
  annotations:
    hourlyCost: "0,88 "
    description: "3 master (4Vcpu, 16Go RAM, 120Go gp2  120iop) +  3 worker ( 4Vcpu,  16Go RAM, 120Go gp2  120iop) - [AWS Londres]"
    descriptionTab: "| 3  | 4  | 16  | 120 | gp2 | 120  | 3  | 4  | 16  | 120 | gp2 | 120  | AWS London"
    descriptionClusterconfig: argocd,pipeline,istio,quaysec,machine,workspaces,couchbase,sso,vault,Knative
    clusterconfig: argocd-project,argocd-deploy,startx,infra,auth,rbac,infra,machine,console,storage,pipeline,istio,couchbase,sso,knative,quaysec,vault,workspaces
compute:
  - name: worker
    hyperthreading: Enabled
    replicas: 3
    platform:
      aws:
        type: c5a.xlarge
        zones:
          - eu-west-2a
          - eu-west-2b
          - eu-west-2c
        rootVolume:
          size: 120
          type: gp2
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      type: c5a.xlarge
      zones:
        - eu-west-2a
        - eu-west-2b
        - eu-west-2c
      rootVolume:
        size: 120
        type: gp2
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineCIDR: 10.11.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  aws:
    region: eu-west-2
    userTags:
      project: sxsf
      cluster: __mycluster__
      profile: deca
      environment: test
      projectOwner: chris
pullSecret: '__ocpPullSecret__'
sshKey: |
  __ocpSshPublickey__
