apiVersion: v1
baseDomain: startx.fr
metadata:
  name: __mycluster__
  annotations:
    hourlyCost: "1,82 "
    description: description: "3 master + worker (16Vcpu, 64Go RAM, 75Go gp2  75iop) - [AWS London]"
    descriptionTab:  "| 3  | 16 | 64  | 75  | gp2 | 75   |    |    |     |     |     |      | AWS London"
    descriptionClusterconfig: argocd,pipeline,istio,quaysec,machine,workspaces,couchbase,sso,vault,Knative
    clusterconfig: argocd-project,argocd-deploy,infra,auth,rbac,infra,machine,console,storage,pipeline,istio,couchbase,sso,knative,quaysec,vault,workspaces
compute:
  - name: worker
    hyperthreading: Enabled
    replicas: 0
    platform:
      aws:
        type: t3a.large
        zones:
          - eu-west-2a
          - eu-west-2b
          - eu-west-2c
        rootVolume:
          iops: 75
          size: 75
          type: gp2
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      type: m5a.4xlarge
      zones:
        - eu-west-2a
        - eu-west-2b
        - eu-west-2c
      rootVolume:
        iops: 100
        size: 100
        type: gp2
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineCIDR: 10.18.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  aws:
    region: eu-west-2
    userTags:
      project: sxsf
      cluster: __mycluster__
      environment: test
      projectOwner: chris
pullSecret: '__ocpPullSecret__'
sshKey: |
  __ocpSshPublickey__
