apiVersion: v1
baseDomain: startx.fr
metadata:
  name: __mycluster__
  annotations:
    hourlyCost: "0,15 "
    description: "1 master + worker (4Vcpu,  8Go RAM, 40Go gp2  40iop) - [AWS Ohio  ]"
    descriptionTab: "| 1  | 4  | 8   | 50  | gp2 | 50   |    |    |     |     |     |      | AWS Ohio  "
    descriptionClusterconfig: argocd
    clusterconfig: argocd-project,argocd-deploy-small,startx,infra,auth,rbac,mustgather,console,storage
compute:
  - name: worker
    hyperthreading: Enabled
    replicas: 0
    platform:
      aws:
        type: t3a.large
        zones:
          - us-east-2a
          - us-east-2b
          - us-east-2c
        rootVolume:
          size: 50
          type: gp2
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 1
  platform:
    aws:
      type: c5.xlarge
      zones:
        - us-east-2a
        - us-east-2b
        - us-east-2c
      rootVolume:
        size: 50
        type: gp2
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineCIDR: 10.18.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  aws:
    region: us-east-2
    userTags:
      project: sxsf
      cluster: __mycluster__
      profile: pico
      environment: test
      projectOwner: chris
pullSecret: '__ocpPullSecret__'
sshKey: |
  __ocpSshPublickey__
