apiVersion: v1
baseDomain: startx.fr
metadata:
  name: __mycluster__
  annotations:
    hourlyCost: "3,97 "
    description: "3 master (8Vcpu, 16Go RAM, 200Go gp2  200iop) +  3 worker ( 8Vcpu,  64Go RAM, 200Go gp2  200iop) - [AWS London]"
    descriptionTab: "| 3  | 8  | 16  | 200 | gp2 | 200  | 3  | 8  | 64  | 200 | gp2 | 200  | AWS London"
    descriptionClusterconfig: argocd,pipeline,istio,quaysec,machine,workspaces,couchbase,sso,vault,Knative,logging,RHACMS,quay,OCS,3Scale
    clusterconfig: argocd-project,argocd-deploy,startx,infra,machine,auth,rbac,console,storage,ocs,pipeline,istio,knative,3scale,quaysec,couchbase,sso,quay,vault,workspaces,logging,acm,acs
compute:
  - name: worker
    hyperthreading: Enabled
    replicas: 3
    platform:
      aws:
        type: r5a.2xlarge
        zones:
          - eu-west-2a
          - eu-west-2b
          - eu-west-2c
        rootVolume:
          iops: 200
          size: 200
          type: gp2
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      type: c5a.2xlarge
      zones:
        - eu-west-2a
        - eu-west-2b
        - eu-west-2c
      rootVolume:
        iops: 200
        size: 200
        type: gp2
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineCIDR: 10.15.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  aws:
    region: eu-west-2
    userTags:
      project: sxsf
      cluster: __mycluster__
      profile: giga
      environment: test
      projectOwner: chris
pullSecret: '__ocpPullSecret__'
sshKey: |
  __ocpSshPublickey__
