apiVersion: v1
baseDomain: startx.fr
metadata:
  name: __mycluster__er__
  annotations:
    hourlyCost: "1,02 "
    description: "3 master + worker (8Vcpu, 32Go RAM, 50Go io1  50iop) - [AWS Paris ]"
    descriptionTab: "| 3  | 8  | 32  | 50  | io1 | 50   |    |    |     |     |     |      | AWS Paris "
    descriptionClusterconfig: argocd,pipeline
    clusterconfig: argocd-project,argocd-deploy,infra,auth,rbac,console,storage,pipeline
compute:
  - name: worker
    hyperthreading: Enabled
    replicas: 0
    platform:
      aws:
        type: t3a.large
        zones:
          - eu-west-3a
          - eu-west-3b
          - eu-west-3c
        rootVolume:
          iops: 100
          size: 50
          type: io1
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      type: t3a.2xlarge
      zones:
        - eu-west-3a
        - eu-west-3b
        - eu-west-3c
      rootVolume:
        iops: 100
        size: 50
        type: io1
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineCIDR: 10.18.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  aws:
    region: eu-west-3
    userTags:
      project: sxsf
      cluster: __mycluster__er__
      profile: milli
      environment: test
      projectOwner: chris
pullSecret: '__ocpPullSecret__'
sshKey: |
  __ocpSshPublickey__
