apiVersion: v1
baseDomain: startx.fr
metadata:
  name: __mycluster__
  annotations:
    hourlyCost: "0,77 "
    description: "3 master + worker (8Vcpu, 32Go RAM, 50Go gp2  50iop) - [AWS Oregon]"
    descriptionTab: "| 3  | 8  | 32  | 50  | gp2 | 50   |    |    |     |     |     |      | AWS Oregon"
    descriptionClusterconfig: argocd,pipeline
    clusterconfig: argocd-project,argocd-deploy-small,startx,infra,auth,rbac,mustgather,console,storage,pipeline
compute:
  - name: worker
    hyperthreading: Enabled
    replicas: 0
    platform:
      aws:
        type: t3a.large
        zones:
          - us-west-2a
          - us-west-2b
          - us-west-2c
        rootVolume:
          size: 40
          type: gp2
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      type: t3a.2xlarge
      zones:
        - us-west-2a
        - us-west-2b
        - us-west-2c
      rootVolume:
        size: 50
        type: gp2
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineCIDR: 10.18.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  aws:
    region: us-west-2
    userTags:
      project: sxsf
      cluster: __mycluster__
      profile: micro
      environment: test
      projectOwner: chris
pullSecret: '__ocpPullSecret__'
sshKey: |
  __ocpSshPublickey__
