apiVersion: v1
baseDomain: startx.fr
metadata:
  name: mycluster
  annotations:
    hourlyCost: "0,99 "
    description: "3 master + worker (16Vcpu, 64Go RAM, 100Go io1  100iop) - [AWS Mumbai]"
    descriptionTab: "| 3  | 16 | 64  | 100 | io1 | 100  |    |    |     |     |     |      | AWS Mumbai"
    descriptionClusterconfig: argocd,pipeline,istio,quaysec
    clusterconfig: argocd-project,argocd-deploy,infra,auth,rbac,console,storage,pipeline,istio,quaysec
compute:
  - name: worker
    hyperthreading: Enabled
    replicas: 0
    platform:
      aws:
        type: t3a.large
        zones:
          - ap-south-1a
          - ap-south-1b
          - ap-south-1c
        rootVolume:
          iops: 50
          size: 50
          type: gp2
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      type: m5a.4xlarge
      zones:
        - ap-south-1a
        - ap-south-1b
        - ap-south-1c
      rootVolume:
        iops: 100
        size: 100
        type: io1
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineCIDR: 10.18.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  aws:
    region: ap-south-1
    userTags:
      project: sxsf
      cluster: mycluster
      profile: deci
      environment: test
      projectOwner: chris
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3N0YXJ0eF9jbDFvZ24ydmNnbGhvYWl3dndpejExajFscnBsdjpDS0U3MFZXQVFRNTc5OU9TNjJEVzA1RlRGOEhLUkhPUTkzWjdUN0pKSlhKVElRMDJOOVo5SVdPTUVGTENGRDU3","email":"cl@startx.fr"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3N0YXJ0eF9jbDFvZ24ydmNnbGhvYWl3dndpejExajFscnBsdjpDS0U3MFZXQVFRNTc5OU9TNjJEVzA1RlRGOEhLUkhPUTkzWjdUN0pKSlhKVElRMDJOOVo5SVdPTUVGTENGRDU3","email":"cl@startx.fr"},"registry.connect.redhat.com":{"auth":"NzI1MDIxN3x1aGMtMU9HbjJWY0dMSE9hSXd2V0laMTFKMUxyUEx2OmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lJek9XWmpPRE0wTkRBeU1EUTBPR0V3WWpReVlqRmxNRGM1T1dNM04yTmhZU0o5Lk9ZTHNsbzlETk5Xb3loODNaanhXb29ZQldFRDl5SVRXd3U4c2paMUZzd1hLdlV1OVRXVVA0a0I1cWpnWS1IQV9CaXhwSmluVVhVWEpHYm5aaU1wZnpYamZ5dzdlUXFqZ2Q4TGZ5TWpEVVlsajN2c1AtMjlUZ25FTkY3cHFON3REMVViSEs2YS1MaUl4RlpQaEpSUUR5V1p6Slg3N2lIVHNIcm1oRmJ4QlNWU25LaWc4YW9JT2R3b01CUHJ4NDJfSnlyZXFCZHlVSDkxNDRKQmR5aG5Ua1hSeFUweFpvTjY2cEg5VlU1MUFmUnpsbVdQMzZfZzkxZ0JnRjU0ZjFGUWVESmJic0dDMU5nUllEVzhrT1cwa1hzWUtTVjhkQjZidk5RU1MyYzlvNC1SNnR5SVY1N3Q1TG5Md3E2X2FaVTZKR3dmU2t3ZE5XczhOZERlNHYyOFVmOTlPdzBpVjA0R2pFTjU2TUQwUXdwY2VZNkFCTGpqUi1DbUUwS2NoMGU1bEc4RXY3Mk1fb1l1cDRiVUxFd2h6bTB0NGtPOWFNTjVEUkU5RW94Qk5aLXFLN25fcnBFQzBNbURIV0M4VDRzRjlpV0hGX293WDJuUnltN28xSWNXeGJ6dHYxZlFCaDl4d3lNT05VLXE2aGh6WEItR2QwdXlvaS1hc2xIZnFQRzRVbjRoN3JURkZjZjJhX2R3VlhaMmhFT2hQeWdnNEpiS2VsVllxMTZWZHg3Yy11Ul82cXZWb2c5d2l3N2s1cEVrd1NPczJlel8wZ0l2R29rSjJDQkQxcU1OaUJVcUM1ZFo3N0Q3WkpENFl4R0kyS3FPemVWM1NQY1dhSjFXVXhyVGtGSzFTMUcyMEVDSkRFUkdYcUhoZzJZNGVSMEMwdEZjTm1mczczZktPelpn","email":"cl@startx.fr"},"registry.redhat.io":{"auth":"NzI1MDIxN3x1aGMtMU9HbjJWY0dMSE9hSXd2V0laMTFKMUxyUEx2OmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lJek9XWmpPRE0wTkRBeU1EUTBPR0V3WWpReVlqRmxNRGM1T1dNM04yTmhZU0o5Lk9ZTHNsbzlETk5Xb3loODNaanhXb29ZQldFRDl5SVRXd3U4c2paMUZzd1hLdlV1OVRXVVA0a0I1cWpnWS1IQV9CaXhwSmluVVhVWEpHYm5aaU1wZnpYamZ5dzdlUXFqZ2Q4TGZ5TWpEVVlsajN2c1AtMjlUZ25FTkY3cHFON3REMVViSEs2YS1MaUl4RlpQaEpSUUR5V1p6Slg3N2lIVHNIcm1oRmJ4QlNWU25LaWc4YW9JT2R3b01CUHJ4NDJfSnlyZXFCZHlVSDkxNDRKQmR5aG5Ua1hSeFUweFpvTjY2cEg5VlU1MUFmUnpsbVdQMzZfZzkxZ0JnRjU0ZjFGUWVESmJic0dDMU5nUllEVzhrT1cwa1hzWUtTVjhkQjZidk5RU1MyYzlvNC1SNnR5SVY1N3Q1TG5Md3E2X2FaVTZKR3dmU2t3ZE5XczhOZERlNHYyOFVmOTlPdzBpVjA0R2pFTjU2TUQwUXdwY2VZNkFCTGpqUi1DbUUwS2NoMGU1bEc4RXY3Mk1fb1l1cDRiVUxFd2h6bTB0NGtPOWFNTjVEUkU5RW94Qk5aLXFLN25fcnBFQzBNbURIV0M4VDRzRjlpV0hGX293WDJuUnltN28xSWNXeGJ6dHYxZlFCaDl4d3lNT05VLXE2aGh6WEItR2QwdXlvaS1hc2xIZnFQRzRVbjRoN3JURkZjZjJhX2R3VlhaMmhFT2hQeWdnNEpiS2VsVllxMTZWZHg3Yy11Ul82cXZWb2c5d2l3N2s1cEVrd1NPczJlel8wZ0l2R29rSjJDQkQxcU1OaUJVcUM1ZFo3N0Q3WkpENFl4R0kyS3FPemVWM1NQY1dhSjFXVXhyVGtGSzFTMUcyMEVDSkRFUkdYcUhoZzJZNGVSMEMwdEZjTm1mczczZktPelpn","email":"cl@startx.fr"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDpTtwoYzhkFW0jDRJwzBdwI1G3v6nx4PV+B2X7/e86tb41agmnt9GkLnPRCeIuanZzcfV/MoD5g4+Bkunnt5UUYlbDNA44UBkSUNq7WdSWq1NR0ObWL1SwL66UDnznqLGdaqgVXswDHef8A+7KHxZ25yzpX9d+MhVhh8gvYH0Jr11gzu439+97kVPJwV9YQs2uKiVIkFLUgGAb+FgI40yBDDMkhZfofaVQIbtC3+I58O0CpeScMFj4lmIpC/nt/kwcSjl/mPkUpPY2B2svemwzJy4SFFLQmvxg0ZUFMdZ3+xdwW/c+ZxTlpWTo+jaCANGL2FUt03V1FRCZnCgw1NMuUUlZu2wq8JSn0JNS02a9HuS0h07Z/bJqw9lvPoXgK1sP49ERylpmlOddSbBJv5//jZ6MzSDAY1/2o46BQInrR1R/MRQyugVh2gCxLbC9zGuJcbD7/WtaDrrPtSFs818tuGQjLz0D3QPeWYLyo4SH5+c15bmF2QQ253QyI/91RQVlyrCaIkwdNWz3nf4Rm/czUoTz3nyAo9PNiVStC19+hqVH/7gwBgtBEC/JMChC0dOGxH7fiPm/BAIhiJHwFtbuJmpznN6leO0P8bNgL8QyumzwCNX7LwTjg1NJS+JlgEUiiIFtCahoi6MPsSqdYW/TxTQZyBd9mqbL/5TjXKVqyw== clarue@startx.fr
