version: 2

mkdocs:
  configuration: mkdocs.yml
# Optionally set the version of Python and requirements required to build your docs
python:
   version: 3.7
#   install:
#   - requirements: docs/requirements.txt
formats:
  - epub
  - pdf
search:
  ranking:
    6-release-history.html: -4
    5-release-lifecycle.html: -3
    2-configure.html: -2
    1-requirements.html: -2
    api/v2/*: 4
  ignore:
    - 404.html