#!/bin/bash
SXCM_PATH=/usr/share/sxcm
SXCM_PROFILES_PATH=$SXCM_PATH/profiles
SXCM_LIB_PATH=$SXCM_PATH/lib
SXCM_COMPLETION_PATH=/etc/bash_completion.d/sxcm
SXCM_BIN_PATH=/usr/bin/sxcm
SXCM_VERSION=main
SXCM_ARCHIVE_URL=https://github.com/startxfr/sxcm/archive/refs/heads/$SXCM_VERSION.zip

if [ `whoami` != 'root' ]
  then
    echo "You must be root to run this installer"
    exit
fi

echo "Install installer dependencies"
yum install unzip curl &> /dev/null
echo "Move to /tmp"
cd /tmp/
echo "Download $SXCM_ARCHIVE_URL"
curl -O -L  $SXCM_ARCHIVE_URL &> /dev/null
echo "Unzip $SXCM_VERSION.zip archive"
unzip -qq $SXCM_VERSION.zip
echo "Install sxcm resources"
cd - &> /dev/null
cd /tmp/sxcm-$SXCM_VERSION &> /dev/null
mv src/completion $SXCM_COMPLETION_PATH
mv src $SXCM_PATH
mv sxcm $SXCM_BIN_PATH
cd - &> /dev/null
rm -rf /tmp/sxcm-$SXCM_VERSION /tmp/$SXCM_VERSION.zip &> /dev/null
echo "sxcm is now installed"
