#!/bin/bash
SXCM_PATH=/usr/share/sxcm
SXCM_PROFILES_PATH=$SXCM_PATH/profiles
SXCM_RESOURCES_PATH=$SXCM_PATH/resources
SXCM_DEMOS_PATH=$SXCM_PATH/demo
SXCM_LIB_PATH=$SXCM_PATH/lib
SXCM_COMPLETION_PATH=/etc/bash_completion.d/sxcm
SXCM_BIN_PATH=/usr/bin/sxcm
SXCM_VERSION=0.1.5
SXCM_ARCHIVE_URL=https://github.com/startxfr/sxcm/archive/refs/tags/$SXCM_VERSION.zip
PKGMNG=dnf
PIPMNG=pip3
SNAPMNG=snap
PKGLIST="curl git atomic-openshift-clients source-to-images bash-completion snapd python3-pip"
SNAPLIST="helm"
PIPLIST="awscli yq jq"

if [ `whoami` != 'root' ]
  then
    echo "You must be root to run this installer"
    exit
fi

echo "Install installer dependencies"
echo -e "Update \e[1m$PKGLIST\e[0m rpm packages \e[1m(root)\e[0m"
$PKGMNG update -y $PKGLIST
echo -e "Update \e[1m$SNAPLIST\e[0m snap packages \e[1m(root)\e[0m"
$SNAPMNG refresh $SNAPLIST
echo -e "Install \e[1m$PIPLIST\e[0m packages \e[1m(user)\e[0m"
$PIPMNG install $PIPLIST --upgrade
echo "Move to /tmp"
cd /tmp/
echo "Download $SXCM_ARCHIVE_URL"
curl -O -L  $SXCM_ARCHIVE_URL &> /dev/null
echo "Unzip $SXCM_VERSION.zip archive"
unzip -qq $SXCM_VERSION.zip
echo "Install sxcm resources"
cd - &> /dev/null
cd /tmp/sxcm-$SXCM_VERSION &> /dev/null
mv src/completion $SXCM_COMPLETION_PATH
mv src/cli $SXCM_BIN_PATH
mv src $SXCM_PATH
cd - &> /dev/null
rm -rf /tmp/sxcm-$SXCM_VERSION /tmp/$SXCM_VERSION.zip &> /dev/null
echo "sxcm is now installed"

