#!/bin/bash
SXCM_PATH=/usr/share/sxcm
SXCM_PROFILES_PATH=$SXCM_PATH/profiles
SXCM_LIB_PATH=$SXCM_PATH/lib
SXCM_VERSION=main

source $SXCM_PATH/cli
source $SXCM_LIB_PATH/core
source $SXCM_LIB_PATH/core-cluster

## Start prog switch
LoadConfig
loadActiveClusterConf



if [[ "$1" != "" ]]; then
    case $1 in
        list)     menuCluster $1 $2 ;;
        create)   menuCluster $1 $2 $3 ;;
        edit)     menuCluster $1 $2 $3 ;;
        switch)   menuCluster $1 $2 ;;
        info)     menuCluster $1 $2 ;;
        deploy)   menuCluster $1 $2 ;;
        update)   menuCluster $1 $2 ;;
        destroy)  menuCluster $1 $2 ;;
        delete)   menuCluster $1 $2 ;;
        switch)   menuCluster $1 $2 ;;
        connect)  menuCluster $1 $2 ;;
        profiles) menuCluster $1 ;;
        current)  menuCluster $1 $2 ;;
        version|--version)  routerVersion;;
        *)        menuUsage $@ ;;
    esac
else
    menuUsage
fi