kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: sxcm-demo-affinity-project
  annotations:
    openshift.io/display-name: Demo STARTX - Node affinity
    openshift.io/documentation-url: https://sxcm.readthedocs.io/en/latest/demo/affinity
    openshift.io/support-url: https://github.com/startxfr/sxcm/issues/new
    openshift.io/generated-by: sxcm
    openshift.io/provider-display-name: STARTX
    description:
      Deployment of severals codeless application with node & pod affinity and anti-affinity 
      directives applied to demonstrate the placement capacity of openshift 4
    iconClass: icon-nodejs
    tags: startx,affinity,node-anti-affinity,node-affinity,demo,dev
  labels:
    component: demo
    template: sxcm-demo-affinity-project
message: |-
  Your demo-affinity demo will be soon deployed in project ${SCOPE}-affinity.
  Monitor the deployement for application availability and
  Follow created route to browse running application

  Scope          : ${SCOPE}
  Environment    : ${ENV}
  Project        : ${NS}

labels:
  template: sxcm-demo-affinity-project
  app.kubernetes.io/managed-by: sxcm
objects: 
- kind: Application
  apiVersion: argoproj.io/v1alpha1
  metadata:
    name: ${NS}-app
    namespace: "${ARGOCD_NS}"
    labels:  &basic_labels
      app.startx.fr/scope: "${SCOPE}"
      app.startx.fr/cluster: "${CLUSTER}"
      app.startx.fr/component: "${NS}"
      app.kubernetes.io/name: "${NS}-application"
      app.kubernetes.io/part-of: ${NS}
      app.kubernetes.io/version: "${VERSION}"
      app.kubernetes.io/component: "${NS}-project"
    annotations: &basic_annotations
      openshift.io/generated-by: sxcm
    finalizers:
      - resources-finalizer.argocd.argoproj.io
  spec:
    destination:
      namespace: "${NS}"
      server: 'https://kubernetes.default.svc'
    info:
      - name: teammail
        value: dev@startx.fr
    project: ${NS}
    source:
      path: charts/example-catalog/
      repoURL: 'https://github.com/startxfr/helm-repository.git'
      targetRevision: master
      helm:
        valueFiles:
          - values-affinity.yaml
        parameters:
          - name: context.scope
            value: "${SCOPE}"
          - name: context.cluster
            value: "${CLUSTER}"
          - name: context.environment
            value: "${ENV}"
          - name: context.version
            value: "${VERSION}"
          - name: context.app
            value: "affinity"
          - name: demo.affinity.namespace
            value: "${NS}"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=false
        - Validate=true
      retry:
        limit: 5
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 20s
parameters:
  - name: NS
    displayName: SXAPI namespace for affinity instance
    description: "Name of the affinity namespace"
    value: demo-affinity
    required: true
  - name: ARGOCD_NS
    displayName: The namespace where argocd server goes to
    description: "Namespace to place argocd server to"
    value: openshift-gitops
    required: true
  - name: SCOPE
    displayName: Project scope
    description: "Project scope (ex: sxv4)"
    value: demo
    required: true
  - name: CLUSTER
    displayName: Cluster name
    description: "Name of the current cluster  (ex: sxsf)"
    value: sxsf
    required: true
  - name: ENV
    displayName: Project environment
    description: "Project environment (ex: dev, factory, preprod or prod)"
    value: dev
    required: true
  - name: VERSION
    displayName: Project version
    description: "Project deployed release"
    value: "1.0.0-dev"
    required: true
  - name: COMPONENT
    displayName: Project service
    description: "Project service"
    value: demo
    required: true