kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: sxcm-argocd-app-template
  annotations:
    openshift.io/display-name: Demo STARTX - ArgoCD samples
    openshift.io/documentation-url: https://sxcm.readthedocs.io/en/latest/demo/argocd
    openshift.io/support-url: https://github.com/startxfr/sxcm/issues/new
    openshift.io/generated-by: sxcm
    openshift.io/provider-display-name: STARTX
    description:
      Template for deploying ArgoCD samples
    iconClass: icon-nodejs
    tags: startx,nodejs,argocd,gitops,sxcm,demo,dev
  labels:
    component: demo
    template: sxcm-argocd-app-template
message: |-
  Your argocd demo applications will be soon deployed in project ${SCOPE}-argocd.
  Monitor the deployement for application availability and
  Follow created route to browse running application

  Scope          : ${SCOPE}
  Environment    : ${ENV}
  Project        : ${NS}

labels:
  template: sxcm-argocd-app-template
  app.kubernetes.io/managed-by: sxcm
objects:
  - kind: Application
    apiVersion: argoproj.io/v1alpha1
    metadata:
      name: ${NS}-export
      namespace: "${ARGOCD_NS}"
      annotations: &basic_annotations
        openshift.io/generated-by: sxcm
      labels: &basic_labels
        app: "argocd-app"
        version: "${VERSION}"
        app.startx.fr/scope: "${SCOPE}"
        app.startx.fr/cluster: "${CLUSTER}"
        app.startx.fr/env: "${ENV}"
        app.startx.fr/component: "argocd"
        app.kubernetes.io/name: "${NS}-export-application"
        app.kubernetes.io/part-of: argocd-app
        app.kubernetes.io/version: "${VERSION}"
        app.kubernetes.io/component: "argocd"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: ${NS}
        server: 'https://kubernetes.default.svc'
      info:
        - name: teammail
          value: dev@startx.fr
      project: ${NS}
      source:
        path: charts/cluster-argocd/
        repoURL: 'https://github.com/startxfr/helm-repository.git'
        targetRevision: HEAD
        helm:
          valueFiles:
            - values-startx.yaml
          parameters:
            - name: context.scope
              value: "${SCOPE}"
            - name: context.cluster
              value: "${CLUSTER}"
            - name: context.environment
              value: "${ENV}"
            - name: context.version
              value: "${VERSION}"
            - name: argocd_export.enabled
              value: "true"
            - name: argocd_export.list[0].name
              value: "demo-export"
            - name: argocd_export.list[0].namespace
              value: "${NS}"
            - name: project.project.name
              value: "${ARGOCD_NS}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  - kind: Application
    apiVersion: argoproj.io/v1alpha1
    metadata:
      name: ${NS}-helm-pod
      namespace: "${ARGOCD_NS}"
      annotations: &basic_annotations
        openshift.io/generated-by: sxcm
      labels: &basic_labels
        app: "argocd-app"
        version: "${VERSION}"
        app.startx.fr/scope: "${SCOPE}"
        app.startx.fr/cluster: "${CLUSTER}"
        app.startx.fr/env: "${ENV}"
        app.startx.fr/component: "argocd"
        app.kubernetes.io/name: "${NS}-helm-pod-application"
        app.kubernetes.io/part-of: argocd-app
        app.kubernetes.io/version: "${VERSION}"
        app.kubernetes.io/component: "argocd"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: ${NS}
        server: 'https://kubernetes.default.svc'
      info:
        - name: teammail
          value: dev@startx.fr
      project: ${NS}
      source:
        path: charts/example-pod/
        repoURL: 'https://github.com/startxfr/helm-repository.git'
        targetRevision: HEAD
        helm:
          valueFiles:
            - values-demo.yaml
          parameters:
            - name: context.scope
              value: "${SCOPE}"
            - name: context.cluster
              value: "${CLUSTER}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  - kind: Application
    apiVersion: argoproj.io/v1alpha1
    metadata:
      name: ${NS}-kustomize-pod
      namespace: "${ARGOCD_NS}"
      labels:
        <<: *basic_labels
        app.kubernetes.io/name: "${NS}-kustomize-pod-application"
      annotations:
        <<: *basic_annotations
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: ${NS}
        server: 'https://kubernetes.default.svc'
      info:
        - name: teammail
          value: dev@startx.fr
      project: ${NS}
      source:
        kustomize:
          namePrefix: argocd-
        path: kustomizes/demo-pod/overlays/default
        repoURL: 'https://github.com/startxfr/kustomize-repository.git'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
parameters:
  - name: NS
    displayName: SXAPI namespace for argocd instance
    description: "Name of the argocd namespace"
    value: demo-argocd
    required: true
  - name: ARGOCD_NS
    displayName: The namespace where argocd server goes to
    description: "Namespace to place argocd server to"
    value: startx-argocd
    required: true
  - name: SCOPE
    displayName: Project scope
    description: "Project scope (ex: sxv4)"
    value: demo
    required: true
  - name: CLUSTER
    displayName: Cluster name
    description: "Name of the current cluster  (ex: sxsf)"
    value: sxsf
    required: true
  - name: ENV
    displayName: Project environment
    description: "Project environment (ex: dev, factory, preprod or prod)"
    value: dev
    required: true
  - name: VERSION
    displayName: Project version
    description: "Project deployed release"
    value: "1.0.0-dev"
    required: true
  - name: COMPONENT
    displayName: Project service
    description: "Project service"
    value: demo
    required: true