kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: sxv4-demo-kubevirt-project-dev-template
  annotations:
    openshift.io/display-name: Demo STARTX - KubeVirt
    openshift.io/documentation-url: https://github.com/startxfr/sxv4/blob/dev/README.md
    openshift.io/support-url: https://github.com/startxfr/sxv4/issues/new
    openshift.io/generated-by: sxcm
    openshift.io/provider-display-name: STARTX
    description:
      Deployment of a KubeVirt infrastructure and a sample application using this infrastructure to 
      demonstrate the Virtual Machine management capacities of KubeVirt solution running under an 
      openshift 4 environment
    iconClass: icon-kubevirt
    tags: startx,kubevirt,demo,dev
  labels:
    template: sxv4-demo-kubevirt-project-dev-template
message: |-
  Your demo project ${NS} for KubeVirt technology is now created.

  Scope          : ${SCOPE}
  Environment    : ${ENV}
  Service        : kubevirt
  Project        : ${NS}

labels:
  template: sxv4-demo-kubevirt-project-dev-template
  app.kubernetes.io/managed-by: sxcm
objects: 
- kind: AppProject
  apiVersion: argoproj.io/v1alpha1
  metadata:
    name: ${NS}
    namespace: "${ARGOCD_NS}"
    labels:  &basic_labels
      app.startx.fr/scope: "${SCOPE}"
      app.startx.fr/cluster: "${CLUSTER}"
      app.startx.fr/component: "${NS}"
      app.kubernetes.io/name: "${NS}-appproject"
      app.kubernetes.io/part-of: ${NS}
      app.kubernetes.io/version: "${VERSION}"
      app.kubernetes.io/component: "${NS}-project"
    annotations: &basic_annotations
      openshift.io/generated-by: sxcm
  spec:
    sourceRepos:
      - '*'
    destinations:
      - namespace: ${NS}
        server: '*'
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    roles:
    - name: dev
      description: Read-only privileges to group dev in ${NS} project
      policies:
      - g, dev, role:readonly
      - p, role:startx-dev, *, get, .${NS}/*, allow
      groups:
      - dev
    - name: ops
      description: Read-only (and sync) privileges to group ops in ${NS} project
      policies:
      - p, role:startx-ops, clusters, get, .${NS}/*, allow
      - p, role:startx-ops, projects, get, .${NS}/*, allow
      - p, role:startx-ops, applications, get, .${NS}/*, allow
      - p, role:startx-ops, applications, sync, .${NS}/*, allow
      - p, role:startx-ops, repositories, get, .${NS}/*, allow
      - p, role:startx-ops, repositories, sync, .${NS}/*, allow
      - p, role:startx-ops, certificates, get, .${NS}/*, allow
      - g, ops, role:startx-ops
      groups:
      - ops
    - name: devops
      description: Read-only privileges to group devops in ${NS} project
      policies:
      - p, role:startx-devops, clusters, get, .${NS}/*, allow
      - p, role:startx-devops, projects, get, .${NS}/*, allow
      - p, role:startx-devops, applications, get, .${NS}/*, allow
      - p, role:startx-devops, repositories, get, .${NS}/*, allow
      - p, role:startx-devops, certificates, get, .${NS}/*, allow
      - g, devops, role:startx-devops
      groups:
      - devops
    - name: admin
      description: All privileges to group admin in ${NS} project
      policies:
      - p, role:startx-admin, *, *, ${NS}/*, allow
      - g, system:cluster-admins, role:admin
      groups:
      - my-oidc-group
      - system:cluster-admins
      - admin
- kind: Application
  apiVersion: argoproj.io/v1alpha1
  metadata:
    name: ${NS}-project
    namespace: "${ARGOCD_NS}"
    labels:
      <<: *basic_labels
      app.kubernetes.io/name: "${NS}-project-application"
    annotations:
      <<: *basic_annotations
    finalizers:
      - resources-finalizer.argocd.argoproj.io
  spec:
    destination:
      namespace: "${NS}"
      server: 'https://kubernetes.default.svc'
    info:
      - name: teammail
        value: dev@startx.fr
    project: ${NS}
    source:
      path: charts/cluster-kubevirt/
      repoURL: 'https://github.com/startxfr/helm-repository.git'
      targetRevision: devel
      helm:
        valueFiles:
          - values-demo.yaml
        parameters:
          - name: context.scope
            value: "${SCOPE}"
          - name: context.cluster
            value: "${CLUSTER}"
          - name: context.environment
            value: "${ENV}"
          - name: context.version
            value: "${VERSION}"
          - name: context.app
            value: "${NS}"
          - name: project.enabled
            value: "true"
          - name: project.project.name
            value: "${NS}"
          - name: project.project.requester
            value: "sxcm"
          - name: operator.enabled
            value: "false"
          - name: hyperconvergedCluster.enabled
            value: "false"
          - name: vms.enabled
            value: "false"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=false
        - Validate=true
      retry:
        limit: 5
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 5m
- kind: Application
  apiVersion: argoproj.io/v1alpha1
  metadata:
    name: ${NS}-vms
    namespace: "${ARGOCD_NS}"
    labels:
      <<: *basic_labels
      app.kubernetes.io/name: "${NS}-vms-application"
    annotations:
      <<: *basic_annotations
    finalizers:
      - resources-finalizer.argocd.argoproj.io
  spec:
    destination:
      namespace: "${NS}"
      server: 'https://kubernetes.default.svc'
    info:
      - name: teammail
        value: dev@startx.fr
    project: ${NS}
    source:
      path: charts/cluster-kubevirt/
      repoURL: 'https://github.com/startxfr/helm-repository.git'
      targetRevision: devel
      helm:
        valueFiles:
          - values-demo.yaml
        parameters:
          - name: context.scope
            value: "${SCOPE}"
          - name: context.cluster
            value: "${CLUSTER}"
          - name: context.environment
            value: "${ENV}"
          - name: context.version
            value: "${VERSION}"
          - name: context.app
            value: "${NS}"
          - name: project.enabled
            value: "false"
          - name: project.project.name
            value: "${NS}"
          - name: project.project.requester
            value: "sxcm"
          - name: operator.enabled
            value: "false"
          - name: hyperconvergedCluster.enabled
            value: "false"
          - name: vms.enabled
            value: "true"
    syncPolicy:
      syncOptions:
        - CreateNamespace=false
        - Validate=true
      retry:
        limit: 3
        backoff:
          duration: 90s
          factor: 2
          maxDuration: 600s
    ignoreDifferences:
      - group: kubevirt.io
        kind: VirtualMachine
        namespace: "${NS}"
        jsonPointers:
          - /spec/template/spec/domain/machine/type
- kind: Application
  apiVersion: argoproj.io/v1alpha1
  metadata:
    name: ${NS}-manpage
    namespace: "${ARGOCD_NS}"
    labels:
      <<: *basic_labels
      app.kubernetes.io/name: "${NS}-manpage-application"
    annotations:
      <<: *basic_annotations
    finalizers:
      - resources-finalizer.argocd.argoproj.io
  spec:
    destination:
      namespace: "${NS}"
      server: 'https://kubernetes.default.svc'
    info:
      - name: teammail
        value: dev@startx.fr
    project: ${NS}
    source:
      path: charts/example-html/
      repoURL: 'https://github.com/startxfr/helm-repository.git'
      targetRevision: devel
      helm:
        valueFiles:
          - values-demo-kubevirt-manpage.yaml
        parameters:
          - name: context.scope
            value: "${SCOPE}"
          - name: context.cluster
            value: "${CLUSTER}"
          - name: context.environment
            value: "${ENV}"
          - name: context.version
            value: "${VERSION}"
          - name: context.app
            value: "manpage"
          - name: html.namespace
            value: "${NS}"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=false
        - Validate=true
      retry:
        limit: 5
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 20s
- kind: Application
  apiVersion: argoproj.io/v1alpha1
  metadata:
    name: ${NS}-kubevirt-app
    namespace: "${ARGOCD_NS}"
    labels:
      <<: *basic_labels
      app.kubernetes.io/name: "${NS}-kubevirt-application"
    annotations:
      <<: *basic_annotations
    finalizers:
      - resources-finalizer.argocd.argoproj.io
  spec:
    destination:
      namespace: "${NS}"
      server: 'https://kubernetes.default.svc'
    info:
      - name: teammail
        value: dev@startx.fr
    project: ${NS}
    source:
      path: charts/example-catalog/
      repoURL: 'https://github.com/startxfr/helm-repository.git'
      targetRevision: devel
      helm:
        valueFiles:
          - values-kubevirt.yaml
        parameters:
          - name: context.scope
            value: "${SCOPE}"
          - name: context.cluster
            value: "${CLUSTER}"
          - name: context.environment
            value: "${ENV}"
          - name: context.version
            value: "${VERSION}"
          - name: context.app
            value: "kubevirt"
          - name: demo.kubevirt.namespace
            value: "${NS}"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=false
        - Validate=true
      retry:
        limit: 5
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 20s
parameters:
  - name: NS
    displayName: The namespace where objects goes to
    description: "Namespace to place objects to"
    value: demo-kubevirt
    required: true
  - name: ARGOCD_NS
    displayName: The namespace where argocd server goes to
    description: "Namespace to place argocd server to"
    value: startx-argocd
    required: true
  - name: SCOPE
    displayName: Project scope
    description: "Project scope (ex: demo)"
    value: demo
    required: true
  - name: CLUSTER
    displayName: Cluster name
    description: "Name of the current cluster  (ex: sxsf)"
    value: sxsf
    required: true
  - name: ENV
    displayName: Project environment
    description: "Project environment (ex: dev, factory, preprod or prod)"
    value: dev
    required: true
  - name: VERSION
    displayName: Project version
    description: "Project deployed release"
    value: "1.0.0-dev"
    required: true
  - name: COMPONENT
    displayName: Project service
    description: "Project service"
    value: demo
    required: true
