kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: sxcm-demo-tekton-demo1-project
  annotations:
    openshift.io/display-name: Demo tekton of a simple task
    openshift.io/documentation-url: https://sxcm.readthedocs.io/en/latest/demo/tekton
    openshift.io/support-url: https://github.com/startxfr/sxcm/issues/new
    openshift.io/generated-by: sxcm
    openshift.io/provider-display-name: STARTX
    description:
      Template deploying required ressource to run a sample demonstration on how to use tekton
      to run a simple standalone task.
    iconClass: icon-nodejs
    tags: startx,nodejs,sxapi,sxcm,demo,dev
  labels:
    template: sxcm-demo-tekton-demo1-project
message: |-
  Your tekton demo 1 ressources are now created.

  Project          : ${NS}

labels:
  project: demo-tekton
  demo: demo1
  app.kubernetes.io/managed-by: sxcm
objects:
  - kind: Task
    apiVersion: tekton.dev/v1beta1
    metadata:
      name: demo1-task
      namespace: "${NS}"
    spec:
      inputs:
        params:
          - name: message
            type: string
            description: The path message to display
            default: "Hello world!"
      steps:
        - name: display-message
          image: registry.redhat.io/ubi7/ubi-minimal
          command: ["echo"]
          args: ["$(inputs.params.message)"]
parameters:
  - name: NS
    displayName: Project scope
    description: "Project scope (ex: demo)"
    value: demo-tekton
  - name: SCOPE
    displayName: Project scope
    description: "Project scope (ex: demo)"
    value: demo
    required: true
  - name: CLUSTER
    displayName: Cluster name
    description: "Name of the current cluster  (ex: sxsf)"
    value: sxsf
    required: true
  - name: ENV
    displayName: Project environment
    description: "Project environment (ex: dev, factory, preprod or prod)"
    value: demo
    required: true
  - name: VERSION
    displayName: Project version
    description: "Project deployed release"
    value: "1.0.0-dev"
    required: true
  - name: HELM_RELEASE
    displayName: Helm repository release
    description: "Branch or release name for the helm repository holding all charts"
    value: devel
