kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: sxv4-demo-tekton-demo3-dev-template
  annotations:
    openshift.io/display-name: Demo tekton of a simple task
    openshift.io/documentation-url: https://github.com/startxfr/sxv4/blob/dev/README.md
    openshift.io/support-url: https://github.com/startxfr/sxv4/issues/new
    openshift.io/generated-by: sxv4-console
    openshift.io/provider-display-name: STARTX
    description:
      Template deploying required ressource to run a sample demonstration on how to use tekton
      to run a simple standalone task.
    iconClass: icon-nodejs
    tags: startx,nodejs,sxapi,sxv4,demo,dev
  labels:
    template: sxv4-demo-tekton-demo3-dev-template
message: |-
  Your tekton demo 3 ressources are now created.

  Project          : ${PROJECT}

labels:
  project: demo-tekton
  demo: demo3
  app.kubernetes.io/managed-by: sxv4-console
objects:
  - kind: Pipeline
    apiVersion: tekton.dev/v1alpha1
    metadata:
      name: demo3-pipeline
      namespace: "${PROJECT}"
    spec:
      params:
        - name: message_one
          type: string
          description: Premier message
          default: Mon premier message par defaut
        - name: message_two
          type: string
          description: Second message
          default: Mon second message par defaut
      tasks:
        - name: premier-message
          taskRef:
            name: demo1-task
          params:
            - name: message
              value: "$(params.message_one)"
        - name: second-message
          taskRef:
            name: demo1-task
          params:
            - name: message
              value: "$(params.message_two)"
parameters:
  - name: PROJECT
    displayName: Project scope
    description: "Project scope (ex: demo)"
    value: demo-tekton
