kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: sxv4-demo-couchbase-jupiter-dev-template
  annotations:
    openshift.io/display-name: "Demo couchbase : Operator v1 - Jupiter"
    openshift.io/documentation-url: https://github.com/startxfr/sxv4/blob/dev/README.md
    openshift.io/support-url: https://github.com/startxfr/sxv4/issues/new
    openshift.io/generated-by: sxcm
    openshift.io/provider-display-name: STARTX
    description:
      Template deploying required ressource to run a sample demonstration on how to use couchbase
      to run a simple standalone task.
    iconClass: icon-nodejs
    tags: startx,nodejs,sxapi,sxv4,demo,dev
  labels:
    template: sxv4-demo-couchbase-jupiter-dev-template
message: |-
  Your couchbase v1.2 Jupiter cluster resources are now created.

  Scope          : ${SCOPE}
  Environment    : ${ENV}
  Namespace      : ${NS}
  Operator       : couchbase-operator.v1.2.2
  Cluster name   : Saturne
  Cluster conf   : v5.5.6-1 - 400Mo data
  Cluster nodes  : 1 data
  Buket name     : demo
  Buket conf     : 200Mo - 1 replica - ${COUCHBASE_BUCKET_TYPE}

labels:
  template: sxv4-demo-couchbase-jupiter-dev-template
  app.kubernetes.io/managed-by: sxcm
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "jupiter-auth"
      namespace: "${NS}"
      labels:
        app: couchbase
        couchbase_cluster: jupiter
    stringData:
      admin: "${COUCHBASE_USER}:${COUCHBASE_PASSWORD}"
      username: "${COUCHBASE_USER}"
      password: "${COUCHBASE_PASSWORD}"
      users: "${COUCHBASE_USER}:${COUCHBASE_PASSWORD}"
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "saturne-auth"
      namespace: "${NS}"
      labels:
        app: couchbase
        couchbase_cluster: saturne
    stringData:
      admin: "${COUCHBASE_USER}:${COUCHBASE_PASSWORD}"
      username: "${COUCHBASE_USER}"
      password: "${COUCHBASE_PASSWORD}"
      users: "${COUCHBASE_USER}:${COUCHBASE_PASSWORD}"
parameters:
  - name: NS
    displayName: The namespace where objects goes to
    description: "Namespace to place objects to"
    value: demo-couchbase
  - name: SCOPE
    displayName: Project scope
    description: "Project scope (ex: demo)"
    value: demo
  - name: CLUSTER
    displayName: Cluster name
    description: "Name of the current cluster  (ex: sxsf)"
    value: sxsf
    required: true
  - name: ENV
    displayName: Project environment
    description: "Project environment (ex: dev, factory, preprod or prod)"
    value: dev
    required: true
  - name: VERSION
    displayName: Project version
    description: "Project deployed release"
    value: "1.0.0-dev"
    required: true
  - name: COMPONENT
    displayName: Project service
    description: "Project service"
    value: couchbase
    required: true
  - name: COUCHBASE_USER
    displayName: Couchbase application user
    description: Database user to create
    value: admin
    required: true
  - name: COUCHBASE_PASSWORD
    displayName: Couchbase password
    description: Database password of the application user
    value: "admin123"
    required: true
    # from: "[a-z0-9]{10}"
    # generate: expression
    # required: true
  - name: COUCHBASE_BUCKET
    displayName: Couchbase bucket
    description: name of the bucket to create for example
    value: demo
    required: true
  - name: COUCHBASE_BUCKET_TYPE
    displayName: Couchbase bucket type
    description: Bucket type for the couchabse bucket (ephemeral, couchbase or memcache)
    value: ephemeral
    required: true
