#!/bin/bash

SXCM_PATH=/usr/share/sxcm
SXCM_PROFILES_PATH=$SXCM_PATH/profiles
SXCM_RESOURCES_PATH=$SXCM_PATH/resources
SXCM_LIB_PATH=$SXCM_PATH/lib

source $SXCM_PATH/config
source $SXCM_LIB_PATH/core
source $SXCM_LIB_PATH/core-version
source $SXCM_LIB_PATH/core-setup
source $SXCM_LIB_PATH/core-cluster
source $SXCM_LIB_PATH/core-profiles
source $SXCM_LIB_PATH/core-resources

## Start prog switch
LoadConfig

if [[ "$1" != "" ]]; then
    case $1 in
        current | switch | list | info | deploy | update | destroy | delete) menuCluster $1 $2 $3 $4 ;;
        import | export | init | create | edit | connect)                    menuCluster $1 $2 $3 $4 $5 ;;
        version | --version | -v)                                            menuResources $1 $2 ;;
        profiles)                                                            menuProfiles $2 ;;
        resources)                                                           menuResources $2 $3;;
        resource)                                                            menuResource $2 $3 $4 $5 $6 ;;
        setup)                                                               menuSetup $@ ;;
        * | -h | --help)                                                     menuUsage $@ ;;
    esac
else
    menuUsage
fi
