#!/bin/bash
SXCM_PATH=/usr/share/sxcm
SXCM_PROFILES_PATH=$SXCM_PATH/profiles
SXCM_RESOURCES_PATH=$SXCM_PATH/resources
SXCM_LIB_PATH=$SXCM_PATH/lib

source $SXCM_PATH/config
source $SXCM_LIB_PATH/core
source $SXCM_LIB_PATH/core-version
source $SXCM_LIB_PATH/core-setup
source $SXCM_LIB_PATH/core-cluster

## Start prog switch
LoadConfig
loadActiveClusterConf



if [[ "$1" != "" ]]; then
    case $1 in
        list)     menuCluster $1 $2 ;;
        import)   menuCluster $1 $2 ;;
        create)   menuCluster $1 $2 $3 ;;
        edit)     menuCluster $1 $2 $3 ;;
        switch)   menuCluster $1 $2 ;;
        info)     menuCluster $1 $2 ;;
        deploy)   menuCluster $1 $2 ;;
        update)   menuCluster $1 $2 ;;
        destroy)  menuCluster $1 $2 ;;
        delete)   menuCluster $1 $2 ;;
        switch)   menuCluster $1 $2 ;;
        connect)  menuCluster $1 $2 ;;
        profiles) menuCluster $1 ;;
        current)  menuCluster $1 $2 ;;
        setup)    menuSetup $@ ;;
        version|--version)  menuVersion;;
        *)        menuUsage $@ ;;
    esac
else
    menuUsage
fi
