#!/bin/bash

# Load the sxcm lib config
SXCM_PATH=/usr/share/sxcm
SXCM_PROFILES_PATH=$SXCM_PATH/profiles
SXCM_RESOURCES_PATH=$SXCM_PATH/resources
SXCM_LIB_PATH=$SXCM_PATH/lib

source $SXCM_PATH/config
source $SXCM_LIB_PATH/core
source $SXCM_LIB_PATH/core-version
source $SXCM_LIB_PATH/core-setup
source $SXCM_LIB_PATH/core-cluster
source $SXCM_LIB_PATH/core-profiles
source $SXCM_LIB_PATH/core-resources

LoadConfig
loadActiveClusterConf

_sxcm_all()
{
    local available="list init create edit switch info deploy update destroy delete connect profiles current version setup import export resources resource"
    local availableService="list create edit info delete associate dissociate enable disable"
    local available2=" "
    if [[ "${COMP_WORDS[1]}" == "edit" ||
            "${COMP_WORDS[1]}" == "switch" ||
            "${COMP_WORDS[1]}" == "info" ||
            "${COMP_WORDS[1]}" == "deploy" ||
            "${COMP_WORDS[1]}" == "update"  ||
            "${COMP_WORDS[1]}" == "destroy"  ||
            "${COMP_WORDS[1]}" == "delete"  ||
            "${COMP_WORDS[1]}" == "connect"  ||
            "${COMP_WORDS[1]}" == "current" ||
            "${COMP_WORDS[1]}" == "export" ]] && [[ "${COMP_CWORD}" == "2" ]]
    then
        available2=$(listClusterConfigs)
    elif [[ "${COMP_WORDS[1]}" == "resource" ]] && [[ "${COMP_CWORD}" == "2" || "${COMP_CWORD}" == "3" || "${COMP_CWORD}" == "4" ]]
    then
        if  [[ "${COMP_WORDS[2]}" == "edit" ]] && [[ "${COMP_CWORD}" == "3" ]]
        then
            available2=$(listResourcesLocal)
        elif  [[ "${COMP_WORDS[2]}" == "info" ||
                "${COMP_WORDS[2]}" == "associate"  ||
                "${COMP_WORDS[2]}" == "dissociate"  ||
                "${COMP_WORDS[2]}" == "enable"  ||
                "${COMP_WORDS[2]}" == "disable" ]] && [[ "${COMP_CWORD}" == "3" ]]
        then
            available2="$(listResourcesLocal) $(listResourcesDefault)"
        elif  [[ "${COMP_WORDS[2]}" == "associate"  ||
                "${COMP_WORDS[2]}" == "dissociate"  ||
                "${COMP_WORDS[2]}" == "enable"  ||
                "${COMP_WORDS[2]}" == "disable" ]] && [[ "${COMP_CWORD}" == "4" ]]
        then
            available2="$(listClusterConfigs)"
        elif  [[ "${COMP_WORDS[2]}" == "delete" ||
                "${COMP_WORDS[2]}" == "edit" ]]
        then

            if  [[ "${COMP_CWORD}" == "3" ]]
            then
                available2=$(listResourcesLocal)
            else
                available2=""
            fi
        elif  [[ "${COMP_CWORD}" == "3" ]] && [[ "${COMP_WORDS[2]}" == "create" ]]
        then
            available2="myresource"
        elif  [[ "${COMP_CWORD}" == "3" ]] && [[ "${COMP_WORDS[2]}" == "list" ]]
        then
            available2=""
        else
            available2=$availableService
        fi
    elif [[ "${COMP_WORDS[1]}" == "edit" ||
            "${COMP_WORDS[1]}" == "switch" ||
            "${COMP_WORDS[1]}" == "info" ||
            "${COMP_WORDS[1]}" == "deploy" ||
            "${COMP_WORDS[1]}" == "update"  ||
            "${COMP_WORDS[1]}" == "destroy"  ||
            "${COMP_WORDS[1]}" == "delete"  ||
            "${COMP_WORDS[1]}" == "connect"  ||
            "${COMP_WORDS[1]}" == "current" ||
            "${COMP_WORDS[1]}" == "export" ]] && [[ "${COMP_CWORD}" == "2" ]]
    then
        available2=$(listClusterConfigs)
    elif [[ "${COMP_WORDS[1]}" == "list" ||
            "${COMP_WORDS[1]}" == "profiles" ||
            "${COMP_WORDS[1]}" == "version" ||
            "${COMP_WORDS[1]}" == "import" ]] && [[ "${COMP_CWORD}" == "2" ]]
    then
        available2=""
    elif [[ "${COMP_WORDS[1]}" == "setup" ]] && [[ "${COMP_CWORD}" == "2" ]]
    then
        available2="aws rhn git all login"
    elif [[ "${COMP_WORDS[1]}" == "init" || "${COMP_WORDS[1]}" == "create" ]]
    then
        if [[ "${COMP_CWORD}" == "2" ]]
        then
            available2="mycluster"
        elif [[ "${COMP_CWORD}" == "3" ]]
        then
            available2=${SXCM_PROFILES_ORDERED[@]}
        else
            available2=""
        fi
    fi
    local suggestions=($(compgen -W "$available" "${COMP_WORDS[1]}"))
    if [[ "${COMP_CWORD}" == "3" ]]
    then
        local suggestions2=($(compgen -W "$available2" "${COMP_WORDS[3]}"))
    elif [[ "${COMP_CWORD}" == "4" ]]
    then
        local suggestions2=($(compgen -W "$available2" "${COMP_WORDS[4]}"))
    else
        local suggestions2=($(compgen -W "$available2" "${COMP_WORDS[2]}"))
    fi
    if [ "${COMP_CWORD}" == "0" ]
    then
        COMPREPLY=("${suggestions[@]}")
    elif [ "${COMP_CWORD}" == "1" ]
    then
        if [ "${#suggestions[@]}" == "1" ]
        then
            local number=$(echo ${suggestions[0]/%\ */})
            COMPREPLY=("$number")
        else
            COMPREPLY=("${suggestions[@]}")
        fi
    elif [[ "${COMP_CWORD}" == "2" || "${COMP_CWORD}" == "3" || "${COMP_CWORD}" == "4" ]]
    then
        if [ "${#suggestions2[@]}" == "${COMP_CWORD}" ]
        then
            local number=$(echo ${suggestions2[0]/%\ */})
            COMPREPLY=("$number")
        else
            COMPREPLY=("${suggestions2[@]}")
        fi
    else
        return 0;
    fi
}

complete -F _sxcm_all sxcm
