#!/bin/bash

# Load the sxcm lib config
SXCM_PATH=/usr/share/sxcm
SXCM_PROFILES_PATH=$SXCM_PATH/profiles
SXCM_RESOURCES_PATH=$SXCM_PATH/resources
SXCM_LIB_PATH=$SXCM_PATH/lib

source $SXCM_PATH/config
source $SXCM_LIB_PATH/core

LoadConfig
loadActiveClusterConf

_sxcm_all()
{

    local available="list create edit switch info deploy update destroy delete connect profiles current version setup import"
    local available2=" "
    if [[ "${COMP_WORDS[1]}" == "edit" ||
            "${COMP_WORDS[1]}" == "switch" ||
            "${COMP_WORDS[1]}" == "info" ||
            "${COMP_WORDS[1]}" == "deploy" ||
            "${COMP_WORDS[1]}" == "update"  ||
            "${COMP_WORDS[1]}" == "destroy"  ||
            "${COMP_WORDS[1]}" == "delete"  ||
            "${COMP_WORDS[1]}" == "connect"  ||
            "${COMP_WORDS[1]}" == "current" ]] && [[ "${COMP_CWORD}" == "2" ]]
    then
        available2=$(getClusterConfigurationList)
    elif [[ "${COMP_WORDS[1]}" == "list" ||
            "${COMP_WORDS[1]}" == "profiles" ||
            "${COMP_WORDS[1]}" == "version" ||
            "${COMP_WORDS[1]}" == "import" ]] && [[ "${COMP_CWORD}" == "2" ]]
    then
        available2=""
    elif [[ "${COMP_WORDS[1]}" == "setup" ]] && [[ "${COMP_CWORD}" == "2" ]]
    then
        available2="aws rhn git all login"
    elif [ "${COMP_WORDS[1]}" == "create" ]
    then
        if [[ "${COMP_WORDS[2]}" == "" ]] || [[ "${COMP_WORDS[2]}" == "\t" ]]
        then
            available2="myClusterName"
        else
            available2=${SXCM_PROFILES_ORDERED[@]}
        fi
    fi
    local suggestions=($(compgen -W "$available" "${COMP_WORDS[1]}"))
    if [[ "${COMP_CWORD}" == "3" ]] || [[ "${COMP_CWORD}" == "2" ]]
    then
        local suggestions2=($(compgen -W "$available2" "${COMP_WORDS[3]}"))
    else
        local suggestions2=($(compgen -W "$available2" "${COMP_WORDS[2]}"))
    fi
    if [ "${COMP_CWORD}" == "0" ]
    then
        COMPREPLY=("${suggestions[@]}")
    elif [ "${COMP_CWORD}" == "1" ]
    then
        if [ "${#suggestions[@]}" == "1" ]
        then
            local number=$(echo ${suggestions[0]/%\ */})
            COMPREPLY=("$number")
        else
            COMPREPLY=("${suggestions[@]}")
        fi
    elif [ "${COMP_CWORD}" == "2" ]
    then
        if [ "${#suggestions2[@]}" == "2" ]
        then
            local number=$(echo ${suggestions2[0]/%\ */})
            COMPREPLY=("$number")
        else
            COMPREPLY=("${suggestions2[@]}")
        fi
    elif [ "${COMP_CWORD}" == "3" ]
    then
        if [ "${#suggestions2[@]}" == "3" ]
        then
            local number=$(echo ${suggestions2[0]/%\ */})
            COMPREPLY=("$number")
        else
            COMPREPLY=("${suggestions2[@]}")
        fi
    else
        return 0;
    fi
}

complete -F _sxcm_all sxcm


